### ISSUE TITLE
Severe error?!

### ISSUE THREAD

**Issue by Computer15776** [Multiverse/Multiverse-Portals#114]
```
[SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.3-AB
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
	at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
	at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:777)
	at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737)
	at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725)
	at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:176)
	at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
	at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
	at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
	at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:552)
	at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:537)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
	at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.NullPointerException
	at com.onarandombox.MultiversePortals.commands.WandCommand.runCommand(WandCommand.java:58)
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:280)
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:144)
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:94)
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:72)
	at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:300)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
	... 14 more
```

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
