### ISSUE TITLE
MultiVerse cannot create portal properly...

### ISSUE THREAD

**Issue by Windwhistle** [Multiverse/Multiverse-Portals#124]
Hello, I am trying to make a SkyLands world and I have everything in, the world was created, the map was successfully implemented. I've never had this problem before but whenever I try to create a portal it says "You need to LEFT click on a block with your wand." and I do use WorldEdit.

My server build is CB #1938, or 1.1 R4. The current version of MultiVerse I use is 2.3-AB which runs for CB 1.1-R4 and CB 1.1-R3.

Here is the log of my latest start-up with WorldEdit and MultiVerse implemented in:

```
174 recipes
27 achievements
23:15:36 [INFO] Starting minecraft server version 1.1
23:15:36 [INFO] Loading properties
23:15:36 [INFO] Starting Minecraft server on *:25565
23:15:36 [WARNING] **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
23:15:36 [WARNING] The server will make no attempt to authenticate usernames. Be
ware.
23:15:36 [WARNING] While this makes the game possible to play without internet a
ccess, it also opens up the ability for hackers to connect with any username the
y choose.
23:15:36 [WARNING] To change this, set "online-mode" to "true" in the server.pro
perties file.
23:15:36 [INFO] This server is running CraftBukkit version git-Bukkit-1.1-R4-b19
38jnks (MC: 1.1) (Implementing API version 1.1-R4)
23:15:36 [SEVERE] Could not load 'plugins\STABMulti-Tool.jar' in folder 'plugins
': Invalid plugin: Jar does not contain plugin.yml
org.bukkit.plugin.InvalidPluginException: Invalid plugin: Jar does not contain p
lugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPlug
inLoader.java:183)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:119)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:164)
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:140)
        at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigur
ationManager.java:52)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:148)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 8 more
23:15:36 [INFO] Starting Minequery server on *:25566
23:15:36 [INFO] [PermissionsEx] sql backend registered!
23:15:36 [INFO] [PermissionsEx] file backend registered!
23:15:36 [INFO] [PermissionsEx] PermissionEx plugin initialized.
23:15:36 [INFO] [PermissionsEx] p2compat backend registered!
23:15:36 [INFO] [PermissionsCompat] Compatibility Layer Initalized!
23:15:37 [INFO] [PermissionsEx] Initializing file backend
23:15:37 [INFO] MLog clients using java 1.4+ standard logging.
23:15:37 [INFO] [LogBlock] Version check: Your version is up to date
23:15:37 [INFO] [LogBlock] Connecting to root@jdbc:mysql://localhost:3306/minecr
aft...
23:15:37 [INFO] [LWC] Loading LWC v4.0.9 (b625-git-be4387f7).
23:15:37 [INFO] LWC: Loading shared objects
23:15:37 [INFO] LWC: Native library: plugins/LWC/lib/native/Windows/amd64/sqlite
jdbc.dll
23:15:37 [INFO] LWC: Protection cache: 0/10000
23:15:37 [INFO] LWC: Loaded 207 locale strings (0 overrides)
23:15:38 [INFO] LWC: Permissions API: NijiPermissions
23:15:38 [INFO] LWC: Currency API: iConomy6Currency
23:15:38 [INFO] LWC: Connecting to MySQL
23:15:38 [INFO] LWC: Performing any necessary database updates
23:15:38 [INFO] LWC: Using: Mysql-connector-java-5.1.14 ( Revision: ${bzr.revisi
on-id} )
23:15:38 [INFO] LWC: Precached 119 protections.
23:15:38 [INFO] LWC: At version: 4.0.9 (b625)
23:15:38 [INFO] Preparing level "world"
23:15:38 [INFO] Default game type: 0
23:15:38 [INFO] Preparing start region for level 0 (Seed: -2973319427566776584)
23:15:38 [INFO] LWC: Latest version: 4.0.9
23:15:39 [INFO] Preparing start region for level 1 (Seed: -2973319427566776584)
23:15:39 [INFO] Preparing spawn area: 44%
23:15:39 [INFO] Preparing start region for level 2 (Seed: -2973319427566776584)
23:15:40 [INFO] [Minequery] Loading Minequery v1.5.
23:15:40 [INFO] [WorldEdit] Loading WorldEdit v5.2.
23:15:40 [INFO] WorldEdit 5.2 enabled.
23:15:40 [INFO] WEPIF: Using the Bukkit Permissions API.
23:15:40 [INFO] WEPIF: Using the Bukkit Permissions API.
23:15:40 [INFO] [Courier] Loading Courier v1.1.1.
23:15:40 [INFO] [Courier] Courier version v1.1.1 is enabled!
23:15:40 [INFO] [LogBlockQuestioner] Loading LogBlockQuestioner v0.02.
23:15:40 [INFO] LogBlockQuestioner v0.02 enabled
23:15:40 [INFO] [PermissionsEx] Loading PermissionsEx v1.18.
23:15:40 [INFO] [PermissionsEx] Superperms support enabled.
23:15:40 [INFO] [PermissionsEx] v1.18 enabled
23:15:40 [INFO] WEPIF: PermissionsEx detected! Using PermissionsEx for permissio
ns.
23:15:40 [INFO] [Multiverse-Core] Loading Multiverse-Core v2.3-AB.
23:15:40 [INFO] [Multiverse-Core] - Version 2.3-AB (API v14) Enabled - By Rigby,
 fernferret, lithium3141 and main--
23:15:40 [INFO] [AllPay] - Version 0.0 - hooked into iConomy 6 for Multiverse-Co
re v2.3-AB
23:15:40 [INFO] [Multiverse-Core] Loading World & Settings - 'world' - Env: NORM
AL - Type: NORMAL & seed: -2973319427566776584
23:15:40 [INFO] [Multiverse-Core] Loading World & Settings - 'world_nether' - En
v: NETHER - Type: NORMAL & seed: -2973319427566776584
23:15:40 [INFO] [Multiverse-Core] Loading World & Settings - 'world_the_end' - E
nv: THE_END - Type: NORMAL & seed: -2973319427566776584
23:15:40 [INFO] [Multiverse-Core] Loading World & Settings - 'SkyLands' - Env: N
ORMAL - Type: NORMAL & seed: 404
23:15:40 [INFO] Preparing start region for level 3 (Seed: 404)
23:15:41 [INFO] [Multiverse-Core] 4 - World(s) loaded.
23:15:41 [INFO] [AutoMessage] Loading AutoMessage v1.5.
23:15:41 [INFO] [AutoMessage] version [1.5] loaded
23:15:41 [INFO] [StopTalkingAutoBan] Loading StopTalkingAutoBan v2.0.4.
23:15:41 [INFO] **********************************************************
23:15:41 [INFO] ** ============= > StopTalkingAutoBan < ==============  **
23:15:41 [INFO] ** ========== TeamM4.com | freebuildxiz.com ==========  **
23:15:41 [INFO] ** =======  Created by: Blackburn & Xizvyrious  ======  **
23:15:41 [INFO] ** =========== Please consider a donation! ===========  **
23:15:41 [INFO] **********************************************************
23:15:41 [INFO] **                Checking for updates...               **
23:15:41 [INFO] >> Unable to check version.. Is the update server down? <<
23:15:41 [INFO] **********************************************************
23:15:41 [INFO] **    [STAB] Ver: [2.0.4r] was enabled successfully!     **
23:15:41 [INFO] **********************************************************
23:15:41 [INFO] [iConomy] Loading iConomy v6.0.8b.
23:15:41 [INFO] [iConomy - Celty] Enabled (57 ms)
23:15:41 [INFO] [AuthMe] Loading AuthMe v2.5.1.
23:15:41 [INFO] [AuthMe] Authme 2.5.1 enabled
23:15:41 [INFO] [SpongeRestore] Loading SpongeRestore v1.7.
23:15:41 [INFO] SpongeRestore version 1.7 is enabled!
23:15:41 [INFO] [Permissions] Loading Permissions v2.7.7.
23:15:41 [INFO] [PermissionsCompat] Compatibility layer enabled.
23:15:41 [INFO] WEPIF: PermissionsEx detected! Using PermissionsEx for permissio
ns.
23:15:41 [INFO] [Modifyworld] Loading Modifyworld v1.18.
23:15:41 [INFO] [Modifyworld] Modifyworld enabled!
23:15:41 [INFO] [NoCheat] Loading NoCheat v3.3.0.
23:15:41 [INFO] [NoCheat] version [3.3.0] is enabled.
23:15:41 [INFO] [Votifier] Loading Votifier v1.6.
23:15:41 [INFO] Loaded vote listener: FlatfileVoteListener
23:15:41 [INFO] Votifier enabled.
23:15:41 [INFO] [ConsoleLikeChat] Loading ConsoleLikeChat v0.1.
23:15:41 [INFO] [ConsoleLikeChat] Version 0.1 enabled.
23:15:41 [INFO] [FalseBookCore] Loading FalseBookCore v0.92.2alpha.
23:15:41 [INFO] [ FalseBook Core ] using PermissionsEx for Permissions!
23:15:41 [INFO] [ FalseBook Core ] FalseBookCore v0.92.2alpha by GeMo enabled!
23:15:41 [INFO] [MobArena] Loading MobArena v0.94.3.24.
23:15:41 [INFO] [MobArena] Payment method found (iConomy version: 6)
23:15:41 [WARNING] [MobArena] Could not find the world for arena 'default'. Usin
g default world! Check the config-file!
23:15:42 [INFO] [MobArena] v0.94.3.24 enabled.
23:15:42 [INFO] [MobDisguise] Loading MobDisguise v1.7.
23:15:42 [INFO] [MobDisguise] by desmin88 version 1.7 enabled.
23:15:42 [INFO] [FalseBookCart] Loading FalseBookCart v0.92.2alpha.
23:15:42 [INFO] 0 locked storagecarts loaded.
23:15:42 [INFO] [ FalseBook Cart ] FalseBookCart v0.92.2alpha by GeMo enabled
23:15:42 [INFO] [Essentials] Loading Essentials v2.8.2.
23:15:42 [INFO] Bukkit version format changed. Version not checked.
23:15:42 [INFO] git-Bukkit-1.1-R4-b1938jnks (MC: 1.1)
23:15:42 [INFO] 1.1-R4
23:15:42 [INFO] File not found: plugins\Essentials\jail.yml
23:15:42 [INFO] Essentials: Using PermissionsEx based permissions.
23:15:42 [INFO] [Essentials] Payment method found (iConomy version: 6)
23:15:42 [INFO] [EssentialsProtect] Loading EssentialsProtect v2.8.2.
23:15:42 [INFO] Initializing c3p0-0.9.1.2 [built 21-May-2007 15:04:56; debug? tr
ue; trace: 10]
23:15:42 [INFO] [FalseBookChat] Loading FalseBookChat v0.92.2alpha.
23:15:42 [INFO] [ FalseBook Chat ] FalseBookChat v0.92.2alpha by GeMo enabled
23:15:42 [INFO] [FalseBookBlock] Loading FalseBookBlock v0.92.2alpha.
23:15:42 [INFO] [ FalseBook Block ] 0 Doors successfully loaded.
23:15:42 [INFO] [ FalseBook Block ] 0 Areas loaded.
23:15:42 [INFO] [ FalseBook Block ] 0 Bridges successfully loaded.
23:15:42 [INFO] [ FalseBook Block ] 2 Cauldrons successfully loaded.
23:15:42 [INFO] [ FalseBook Block ] 3100 Books loaded!
23:15:42 [INFO] [ FalseBook Block ] 35 protected gateblocks successfully loaded.

23:15:42 [INFO] [ FalseBook Block ] FalseBookBlock v0.92.2alpha by GeMo enabled
23:15:42 [INFO] [EssentialsSpawn] Loading EssentialsSpawn v2.8.2.
23:15:42 [INFO] [Multiverse-Portals] Loading Multiverse-Portals v2.3-AB.
23:15:42 [INFO] [Multiverse-Portals] - Version 2.3-AB Enabled - By Rigby and fer
nferret
23:15:42 [WARNING] [Multiverse-Portals]  Failed Parsing Location for: NormalPort
 (Format Error, was expecting: `X,Y,Z:X,Y,Z`, but got: ``)
23:15:42 [WARNING] [Multiverse-Portals]  Portal NormalPort has an invalid LOCATI
ON!
23:15:42 [SEVERE] Error occurred while enabling Multiverse-Portals v2.3-AB (Is i
t up to date?): The permission multiverse.portal.access.normalport is already de
fined!
java.lang.IllegalArgumentException: The permission multiverse.portal.access.norm
alport is already defined!
        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManag
er.java:609)
        at com.onarandombox.MultiversePortals.MVPortal.<init>(MVPortal.java:50)
        at com.onarandombox.MultiversePortals.MVPortal.loadMVPortalFromConfig(MV
Portal.java:111)
        at com.onarandombox.MultiversePortals.MultiversePortals.loadPortals(Mult
iversePortals.java:188)
        at com.onarandombox.MultiversePortals.MultiversePortals.onEnable(Multive
rsePortals.java:115)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:230)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:1057)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:380)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:199)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:182
)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:357)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:344)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
23:15:42 [INFO] [LogBlock] Loading LogBlock v1.50.
23:15:42 [INFO] [LogBlock] Permissions plugin found.
23:15:42 [INFO] [LogBlock] Using own chest access API
23:15:42 [INFO] [LogBlock] Scheduled consumer with bukkit scheduler.
23:15:42 [INFO] LogBlock v1.50 by DiddiZ enabled.
23:15:42 [INFO] [dynmap] Loading dynmap v0.32-884.
23:15:42 [INFO] [dynmap] Using Permissions 2.7.7 for access control
23:15:43 [INFO] [dynmap] Loaded 15 shaders.
23:15:44 [INFO] [dynmap] Loaded 82 perspectives.
23:15:44 [INFO] [dynmap] Loaded 12 lightings.
23:15:44 [INFO] [dynmap] version 0.32-884 is enabled - core version 0.32-83
23:15:44 [INFO] [dynmap] Loaded 3 maps of world 'world'.
23:15:44 [INFO] [dynmap] Loaded 2 maps of world 'world_nether'.
23:15:44 [INFO] [dynmap] Loaded 2 maps of world 'world_the_end'.
23:15:44 [INFO] [dynmap] Loaded 3 maps of world 'SkyLands'.
23:15:44 [INFO] [dynmap] Enabled
23:15:44 [INFO] [MobBounty] Loading MobBounty v4.2.
23:15:44 [INFO] [MobBounty] v4.2 (Oxygen) enabled.
23:15:44 [INFO] [MobBounty] Developed by: [Mattera, Steven].
23:15:44 [INFO] [MobBounty] Config loaded.
23:15:44 [INFO] [MobBounty] Permission plugin was found (PermissionsEx v1.18).
23:15:44 [INFO] [MobBounty] Payment plugin iConomy v6 found!
23:15:44 [INFO] [FalseBookIC] Loading FalseBookIC v0.92.2alpha.
23:15:44 [INFO] [ FalseBook IC ] Selftriggered ICs are executing aprox. every 50
0ms.
23:15:44 [INFO] [ FalseBook IC ] 'DetectionPackage' imported '12' ICs.
23:15:44 [INFO] [ FalseBook IC ] 'SelftriggeredPackage' imported '17' ICs.
23:15:44 [INFO] [ FalseBook IC ] 'StandardPackage' imported '36' ICs.
23:15:44 [INFO] [ FalseBook IC ] 'WorldEditPackage' imported '17' ICs.
23:15:44 [INFO] [ FalseBook IC ] FalseBookIC v0.92.2alpha by GeMo enabled
23:15:44 [INFO] [ChestShop] Loading ChestShop v3.35.
23:15:44 [INFO] [ChestShop] Permissions version 2.7.7 loaded.
23:15:44 [INFO] [ChestShop] LWC version 4.0.9 (b625-git-be4387f7) loaded.
23:15:44 [INFO] [ChestShop] iConomy version 6.0.8b loaded.
23:15:44 [INFO] [ChestShop] Essentials version 2.8.2 loaded.
23:15:44 [INFO] [ChestShop] iConomy loaded.
23:15:44 [INFO] [ChestShop] version 3.35 initialized!
23:15:44 [INFO] [EssentialsChat] Loading EssentialsChat v2.8.2.
23:15:45 [INFO] [FalseBookExtra] Loading FalseBookExtra v0.92.2alpha.
23:15:45 [INFO] [ FalseBook Extra ] 2 protected blocks loaded.
23:15:45 [INFO] [ FalseBook Extra ] FalseBookExtra v0.92.2alpha by GeMo enabled
23:15:45 [INFO] [Factions] Loading Factions v1.6.5.
23:15:45 [INFO] [Factions v1.6.5] === ENABLE START ===
23:15:45 [INFO] [Factions v1.6.5] Loading board from disk
23:15:45 [INFO] [Factions v1.6.5] Found and will integrate chat with EssentialsC
hat v2.8.2
23:15:45 [INFO] [Factions v1.6.5] Economy integration is disabled, and the plugi
n "Vault" is not installed.
23:15:45 [INFO] [Factions v1.6.5] Successfully hooked into LWC! Integration is c
urrently disabled, though ("lwcIntegration").
23:15:45 [INFO] [Factions v1.6.5] === ENABLE DONE (Took 236ms) ===
23:15:45 [INFO] Server permissions file permissions.yml is empty, ignoring it
23:15:45 [INFO] Done (7.472s)! For help, type "help" or "?"
23:15:48 [INFO] [ FalseBook IC ] Loaded selftriggered ICs: 0 done
23:15:48 [INFO] [ FalseBook IC ] Failed selftriggered ICs: 0 failed
```

Any ideas? I really want to get this Sky Land portal going! :(

**Comment by FernFerret** [comment]
Now we're going way back. Not sure if Skylands is still a thing anymore...

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
