### ISSUE TITLE
[SEVERE] Could not pass event org.bukkit.event.player.PlayerMoveEvent to Multiverse-Portals

### ISSUE THREAD

**Issue by BurtGummer** [Multiverse/Multiverse-Portals#125]
Hi,
i have update my Multiverse Plugins from 2.2-AB to 2.3-AB. Now, i can't enter a normal world (before the update i could). If i try to go through the portal, i can't go and the console say:

```
2012-02-27 18:11:53 [SEVERE] Could not pass event org.bukkit.event.player.PlayerMoveEvent to Multiverse-Portals
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$103.execute(JavaPluginLoader.java:1026)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:61)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:460)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:191)
        at net.minecraft.server.Packet10Flying.handle(SourceFile:126)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:537)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.bukkit.plugin.java.JavaPluginLoader$103.execute(JavaPluginLoader.java:1024)
        ... 10 more
Caused by: java.util.MissingFormatArgumentException: Format specifier 's'
        at java.util.Formatter.format(Formatter.java:2432)
        at java.util.Formatter.format(Formatter.java:2367)
        at java.lang.String.format(String.java:2769)
        at com.fernferret.allpay.multiverse.GenericBank.showReceipt(GenericBank.java:385)
        at com.fernferret.allpay.multiverse.EssentialsBank.takeMoney(EssentialsBank.java:36)
        at com.fernferret.allpay.multiverse.GenericBank.take(GenericBank.java:168)
        at com.onarandombox.MultiversePortals.listeners.MVPPlayerListener.playerMove(MVPPlayerListener.java:223)
        ... 14 more
2012-02-27 18:12:38 [SEVERE] Could not pass event org.bukkit.event.player.PlayerMoveEvent to Multiverse-Portals
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$103.execute(JavaPluginLoader.java:1026)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:61)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:460)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:191)
        at net.minecraft.server.Packet10Flying.handle(SourceFile:126)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:537)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.bukkit.plugin.java.JavaPluginLoader$103.execute(JavaPluginLoader.java:1024)
        ... 10 more
Caused by: java.util.MissingFormatArgumentException: Format specifier 's'
        at java.util.Formatter.format(Formatter.java:2432)
        at java.util.Formatter.format(Formatter.java:2367)
        at java.lang.String.format(String.java:2769)
        at com.fernferret.allpay.multiverse.GenericBank.showReceipt(GenericBank.java:385)
        at com.fernferret.allpay.multiverse.EssentialsBank.takeMoney(EssentialsBank.java:36)
        at com.fernferret.allpay.multiverse.GenericBank.take(GenericBank.java:168)
        at com.onarandombox.MultiversePortals.listeners.MVPPlayerListener.playerMove(MVPPlayerListener.java:223)
        ... 14 more
```

Any Ideas whats wrong? Other worlds i can enter. I use CB 1.1-R4

**Comment by RogerRoger101** [comment]
3 years later, still not so eagerly waiting :)

**Comment by FernFerret** [comment]
So... This issue was opened with 2.2 and 2.3. Responses of "Still waiting" (while yes, we don't have a great track record of checking the issues here in the past :smile:) aren't really good ways of responding to a ticket like this. Please post your own debug info to help as well. With that said, Here's my generic speech on this one. Please reopen if it's still happening (see below for links on how to write good reports).

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
