### ISSUE TITLE
[SEVERE] Could not pass event MVConfigReloadEvent to Multiverse-Portals

### ISSUE THREAD

**Issue by Bronski** [Multiverse/Multiverse-Portals#206]
CB bild 2457 / MV b628 / MVP b645

```
2012-11-14 06:19:42 [INFO] Bronski issued server command: /mv reload
2012-11-14 06:19:44 [INFO] [Multiverse-Core] 23 - World(s) loaded.
2012-11-14 06:19:44 [SEVERE] Could not pass event MVConfigReloadEvent to Multiverse-Portals v2.5-b645
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
	at com.onarandombox.MultiverseCore.commands.ReloadCommand.runCommand(ReloadCommand.java:49)
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:882)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:185)
	at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:504)
	at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:911)
	at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:824)
	at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:806)
	at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
	at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
	at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:111)
	at net.minecraft.server.ServerConnection.b(SourceFile:35)
	at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
	at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:578)
	at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:215)
	at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:495)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:428)
	at net.minecraft.server.ThreadServerApplication.run(SourceFile:818)
Caused by: java.lang.NullPointerException
	at com.onarandombox.MultiversePortals.utils.PortalManager.removeFromWorldChunkPortals(PortalManager.java:351)
	at com.onarandombox.MultiversePortals.utils.PortalManager.removePortal(PortalManager.java:150)
	at com.onarandombox.MultiversePortals.utils.PortalManager.removeAll(PortalManager.java:262)
	at com.onarandombox.MultiversePortals.MultiversePortals.reloadConfigs(MultiversePortals.java:378)
	at com.onarandombox.MultiversePortals.listeners.MVPCoreListener.configReload(MVPCoreListener.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
	... 24 more
```

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
