### ISSUE TITLE
Server crash on /mvp create

### ISSUE THREAD

**Issue by stkeroro** [Multiverse/Multiverse-Portals#214]
Server crash when do /mvp creane

```
2012-11-30 17:11:40 [INFO] burbujah issued server command: /mvp create gamerz
2012-11-30 17:11:41 [INFO] WEAPI
2012-11-30 17:11:59 [WARNING] [Server] The main thread failed to respond after 10 seconds
2012-11-30 17:11:59 [WARNING] [Server] Probable Plugin cause: 'Multiverse-Portals'
2012-11-30 17:11:59 [WARNING] [Server] What follows is the stack trace of the main thread
2012-11-30 17:11:59 [WARNING] [Server]    at java.util.WeakHashMap.remove(WeakHashMap.java:684)
2012-11-30 17:11:59 [WARNING] [Server]    at org.bukkit.plugin.SimplePluginManager.unsubscribeFromPermission(SimplePluginManager.java:636)
2012-11-30 17:11:59 [WARNING] [Server]    at org.bukkit.permissions.PermissibleBase.clearPermissions(PermissibleBase.java:169)
2012-11-30 17:11:59 [WARNING] [Server]    at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:149)
2012-11-30 17:11:59 [WARNING] [Server]    at org.bukkit.craftbukkit.entity.CraftHumanEntity.recalculatePermissions(CraftHumanEntity.java:132)
2012-11-30 17:11:59 [WARNING] [Server]    at org.bukkit.plugin.SimplePluginManager.dirtyPermissibles(SimplePluginManager.java:615)
2012-11-30 17:11:59 [WARNING] [Server]    at org.bukkit.plugin.SimplePluginManager.calculatePermissionDefault(SimplePluginManager.java:603)
2012-11-30 17:11:59 [WARNING] [Server]    at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:576)
2012-11-30 17:11:59 [WARNING] [Server]    at com.onarandombox.MultiversePortals.MVPortal.init(MVPortal.java:94)
2012-11-30 17:11:59 [WARNING] [Server]    at com.onarandombox.MultiversePortals.MVPortal.<init>(MVPortal.java:63)
2012-11-30 17:11:59 [WARNING] [Server]    at com.onarandombox.MultiversePortals.MVPortal.<init>(MVPortal.java:236)
2012-11-30 17:11:59 [WARNING] [Server]    at com.onarandombox.MultiversePortals.utils.PortalManager.addPortal(PortalManager.java:126)
2012-11-30 17:11:59 [WARNING] [Server]    at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:62)
2012-11-30 17:11:59 [WARNING] [Server]    at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
2012-11-30 17:11:59 [WARNING] [Server]    at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
2012-11-30 17:11:59 [WARNING] [Server]    at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
2012-11-30 17:11:59 [WARNING] [Server]    at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71)
2012-11-30 17:11:59 [WARNING] [Server]    at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:328)
2012-11-30 17:11:59 [WARNING] [Server]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2012-11-30 17:11:59 [WARNING] [Server]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
2012-11-30 17:11:59 [WARNING] [Server]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:502)
2012-11-30 17:11:59 [WARNING] [Server]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:985)
2012-11-30 17:11:59 [WARNING] [Server]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:903)
2012-11-30 17:11:59 [WARNING] [Server]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:858)
2012-11-30 17:11:59 [WARNING] [Server]    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
2012-11-30 17:11:59 [WARNING] [Server]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:290)
2012-11-30 17:11:59 [WARNING] [Server]    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:113)
2012-11-30 17:11:59 [WARNING] [Server]    at net.minecraft.server.ServerConnection.b(SourceFile:39)
2012-11-30 17:11:59 [WARNING] [Server]    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
2012-11-30 17:11:59 [WARNING] [Server]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:595)
2012-11-30 17:11:59 [WARNING] [Server]    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
2012-11-30 17:12:11 [WARNING] [Server] The main thread is still stuck, current loop line is:
2012-11-30 17:12:11 [WARNING] [Server]    at com.onarandombox.MultiversePortals.MVPortal.<init>(MVPortal.java:63)
2012-11-30 17:12:11 [WARNING] [Server] This appears to be plugin 'Multiverse-Portals'!
```

**Comment by FernFerret** [comment]
Could be due to an enormous portal being filled...

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
