### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by G4meM0ment** [Multiverse/Multiverse-Portals#278]
Hey,
I first get an error while starting the server, but the plugin seems to work.
If I try to import a world I get this error:

```
G4meM0ment issued server command: /mv import OrbiA normal
2013-08-16 13:25:11 [INFO] G4meM0ment: Starting import of world 'OrbiA'...[m
2013-08-16 13:25:11 [INFO] [Multiverse-Core] Loading World & Settings - 'OrbiA' - Env: NORMAL - Type: null
2013-08-16 13:25:11 [WARNING] [Multiverse-Core] Spawn location from world.dat file was unsafe. Adjusting...
2013-08-16 13:25:11 [WARNING] [Multiverse-Core] Original Location: X: 0 Y: 87 Z: 0 P: 0 Y: 0 
2013-08-16 13:25:11 [INFO] [Multiverse-Core] New Spawn for 'OrbiA' is located at: OrbiA:-0,50,87,00,-0,50:0,00:0,00
2013-08-16 13:25:11 [SEVERE] java.lang.NullPointerException
2013-08-16 13:25:11 [SEVERE] 	at com.onarandombox.MultiverseCore.utils.WorldManager.saveWorldsConfig(WorldManager.java:739)
2013-08-16 13:25:11 [SEVERE] 	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:236)
2013-08-16 13:25:11 [SEVERE] 	at com.onarandombox.MultiverseCore.commands.ImportCommand.runCommand(ImportCommand.java:147)
2013-08-16 13:25:11 [SEVERE] 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
2013-08-16 13:25:11 [SEVERE] 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
2013-08-16 13:25:11 [SEVERE] 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
2013-08-16 13:25:11 [SEVERE] 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:882)
2013-08-16 13:25:11 [SEVERE] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2013-08-16 13:25:11 [SEVERE] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:191)
2013-08-16 13:25:11 [SEVERE] 	at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchCommand(CraftServer.java:523)
2013-08-16 13:25:11 [SEVERE] 	at net.minecraft.server.v1_6_R2.PlayerConnection.handleCommand(PlayerConnection.java:954)
2013-08-16 13:25:11 [SEVERE] 	at net.minecraft.server.v1_6_R2.PlayerConnection.chat(PlayerConnection.java:872)
2013-08-16 13:25:11 [SEVERE] 	at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:829)
2013-08-16 13:25:11 [SEVERE] 	at net.minecraft.server.v1_6_R2.Packet3Chat.handle(SourceFile:49)
2013-08-16 13:25:11 [SEVERE] 	at net.minecraft.server.v1_6_R2.NetworkManager.b(NetworkManager.java:296)
2013-08-16 13:25:11 [SEVERE] 	at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:116)
2013-08-16 13:25:11 [SEVERE] 	at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
2013-08-16 13:25:11 [SEVERE] 	at net.minecraft.server.v1_6_R2.DedicatedServerConnection.b(SourceFile:30)
2013-08-16 13:25:11 [SEVERE] 	at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:590)
2013-08-16 13:25:11 [SEVERE] 	at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
2013-08-16 13:25:11 [SEVERE] 	at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
2013-08-16 13:25:11 [SEVERE] 	at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
2013-08-16 13:25:11 [SEVERE] 	at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
2013-08-16 13:25:20 [INFO]
```

Hope you can fix this.

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
