### ISSUE TITLE
Portal Error

### ISSUE THREAD

**Issue by ghost** [Multiverse/Multiverse-Portals#303]
[13:00:55 ERROR]: Could not pass event PlayerMoveEvent to Multiverse-Portals v2.4-b548
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.1-7-g15db099-b2973jnks]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.1-7-g15db099-b2973jnks]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:481) [craftbukkit.jar:git-Bukkit-1.7.2-R0.1-7-g15db099-b2973jnks]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:466) [craftbukkit.jar:git-Bukkit-1.7.2-R0.1-7-g15db099-b2973jnks]
	at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java:227) [craftbukkit.jar:git-Bukkit-1.7.2-R0.1-7-g15db099-b2973jnks]
	at net.minecraft.server.v1_7_R1.PacketPlayInFlying.a(SourceFile:137) [craftbukkit.jar:git-Bukkit-1.7.2-R0.1-7-g15db099-b2973jnks]
	at net.minecraft.server.v1_7_R1.PacketPlayInPosition.handle(SourceFile:63) [craftbukkit.jar:git-Bukkit-1.7.2-R0.1-7-g15db099-b2973jnks]
	at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:146) [craftbukkit.jar:git-Bukkit-1.7.2-R0.1-7-g15db099-b2973jnks]
	at net.minecraft.server.v1_7_R1.ServerConnection.c(SourceFile:134) [craftbukkit.jar:git-Bukkit-1.7.2-R0.1-7-g15db099-b2973jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:655) [craftbukkit.jar:git-Bukkit-1.7.2-R0.1-7-g15db099-b2973jnks]
	at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:250) [craftbukkit.jar:git-Bukkit-1.7.2-R0.1-7-g15db099-b2973jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:545) [craftbukkit.jar:git-Bukkit-1.7.2-R0.1-7-g15db099-b2973jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:457) [craftbukkit.jar:git-Bukkit-1.7.2-R0.1-7-g15db099-b2973jnks]
	at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit.jar:git-Bukkit-1.7.2-R0.1-7-g15db099-b2973jnks]
Caused by: java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.MultiverseCore.getBank()Lcom/fernferret/allpay/multiverse/GenericBank;
	at com.onarandombox.MultiversePortals.listeners.MVPPlayerListener.playerMove(MVPPlayerListener.java:240) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_45]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.1-7-g15db099-b2973jnks]
	... 13 more

NEED HELP THANKS!

**Comment by TWSSYesterday** [comment]
No longer the case.

**Comment by FernFerret** [comment]
Heh this user doesn't even exist anymore

**Comment by TWSSYesterday** [comment]
:D At least we're doing catch up! Do you even skype anymore @FernFerret lol

**Comment by FernFerret** [comment]
Nope, I'm in our IRC channel though.
