### ISSUE TITLE
Could not pass event PlayerMoveEvent to Multiverse-Portals v2.4-b548

### ISSUE THREAD

**Issue by Devonshiresab** [Multiverse/Multiverse-Portals#306]
[13:18:16] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Multiverse-Portals v2.4-b548
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[cj.jar:git-Spigot-1330]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[cj.jar:git-Spigot-1330]
	at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[cj.jar:git-Spigot-1330]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:487) [cj.jar:git-Spigot-1330]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:472) [cj.jar:git-Spigot-1330]
	at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java:247) [cj.jar:git-Spigot-1330]
	at net.minecraft.server.v1_7_R1.PacketPlayInFlying.a(SourceFile:137) [cj.jar:git-Spigot-1330]
	at net.minecraft.server.v1_7_R1.PacketPlayInPosition.handle(SourceFile:63) [cj.jar:git-Spigot-1330]
	at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:147) [cj.jar:git-Spigot-1330]
	at net.minecraft.server.v1_7_R1.ServerConnection.c(ServerConnection.java:77) [cj.jar:git-Spigot-1330]
	at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:700) [cj.jar:git-Spigot-1330]
	at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [cj.jar:git-Spigot-1330]
	at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:562) [cj.jar:git-Spigot-1330]
	at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:469) [cj.jar:git-Spigot-1330]
	at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [cj.jar:git-Spigot-1330]
Caused by: java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.MultiverseCore.getBank()Lcom/fernferret/allpay/multiverse/GenericBank;
	at com.onarandombox.MultiversePortals.listeners.MVPPlayerListener.playerMove(MVPPlayerListener.java:240) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_11]
	at java.lang.reflect.Method.invoke(Method.java:601) ~[?:1.7.0_11]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:318) ~[cj.jar:git-Spigot-1330]
	... 14 more

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
