### ISSUE TITLE
I can`t create portals

### ISSUE THREAD

**Issue by horatyu** [Multiverse/Multiverse-Portals#311]
I want to create a portal but I have this error: 

```
[16:58:43] [Server thread/INFO]: Gamer027 issued server command: /mvp create test
[16:58:43] [Server thread/INFO]: WEAPI
[16:58:43] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.5-b710
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180) ~[minecraft_server.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at org.bukkit.craftbukkit.v1_7_R2.CraftServer.dispatchCommand(CraftServer.java:696) ~[minecraft_server.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at net.minecraft.server.v1_7_R2.PlayerConnection.handleCommand(PlayerConnection.java:952) [minecraft_server.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at net.minecraft.server.v1_7_R2.PlayerConnection.a(PlayerConnection.java:814) [minecraft_server.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at net.minecraft.server.v1_7_R2.PacketPlayInChat.a(PacketPlayInChat.java:28) [minecraft_server.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at net.minecraft.server.v1_7_R2.PacketPlayInChat.handle(PacketPlayInChat.java:47) [minecraft_server.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at net.minecraft.server.v1_7_R2.NetworkManager.a(NetworkManager.java:147) [minecraft_server.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at net.minecraft.server.v1_7_R2.ServerConnection.c(SourceFile:134) [minecraft_server.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at net.minecraft.server.v1_7_R2.MinecraftServer.v(MinecraftServer.java:657) [minecraft_server.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at net.minecraft.server.v1_7_R2.DedicatedServer.v(DedicatedServer.java:250) [minecraft_server.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at net.minecraft.server.v1_7_R2.MinecraftServer.u(MinecraftServer.java:548) [minecraft_server.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at net.minecraft.server.v1_7_R2.MinecraftServer.run(MinecraftServer.java:459) [minecraft_server.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	at net.minecraft.server.v1_7_R2.ThreadServerApplication.run(SourceFile:618) [minecraft_server.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;
	at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:168) ~[?:?]
	at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
	at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:336) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Bukkit-1.7.2-R0.3-14-g8f8716c-b3042jnks]
	... 13 more
```

**Comment by FernFerret** [comment]
I bet this got resolved with https://github.com/Multiverse/Multiverse-Portals/commit/a6694b955eff8f399da736c941423bb16a800287, but if not, read below.

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
