### ISSUE TITLE
 Could not pass event PlayerMoveEvent to Multiverse-Portals v2.4-b548

### ISSUE THREAD

**Issue by crazyfabio** [Multiverse/Multiverse-Portals#335]
[13:39:38 ERROR]: Could not pass event PlayerMoveEvent to Multiverse-Portals v2.4-b548
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[spigot175_0_1.jar:git-Spigot-1366]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot175_0_1.jar:git-Spigot-1366]
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[spigot175_0_1.jar:git-Spigot-1366]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot175_0_1.jar:git-Spigot-1366]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot175_0_1.jar:git-Spigot-1366]
        at net.minecraft.server.v1_7_R2.PlayerConnection.a(PlayerConnection.java:247) [spigot175_0_1.jar:git-Spigot-1366]
        at net.minecraft.server.v1_7_R2.PacketPlayInFlying.a(SourceFile:137) [spigot175_0_1.jar:git-Spigot-1366]
        at net.minecraft.server.v1_7_R2.PacketPlayInPosition.handle(SourceFile:63) [spigot175_0_1.jar:git-Spigot-1366]
        at net.minecraft.server.v1_7_R2.NetworkManager.a(NetworkManager.java:148) [spigot175_0_1.jar:git-Spigot-1366]
        at net.minecraft.server.v1_7_R2.ServerConnection.c(ServerConnection.java:77) [spigot175_0_1.jar:git-Spigot-1366]
        at net.minecraft.server.v1_7_R2.MinecraftServer.v(MinecraftServer.java:703) [spigot175_0_1.jar:git-Spigot-1366]
        at net.minecraft.server.v1_7_R2.DedicatedServer.v(DedicatedServer.java:273) [spigot175_0_1.jar:git-Spigot-1366]
        at net.minecraft.server.v1_7_R2.MinecraftServer.u(MinecraftServer.java:566) [spigot175_0_1.jar:git-Spigot-1366]
        at net.minecraft.server.v1_7_R2.MinecraftServer.run(MinecraftServer.java:472) [spigot175_0_1.jar:git-Spigot-1366]
        at net.minecraft.server.v1_7_R2.ThreadServerApplication.run(SourceFile:618) [spigot175_0_1.jar:git-Spigot-1366]
Caused by: java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.MultiverseCore.getBank()Lcom/fernferret/allpay/multiverse/GenericBank;
        at com.onarandombox.MultiversePortals.listeners.MVPPlayerListener.playerMove(MVPPlayerListener.java:240) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_25]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[spigot175_0_1.jar:git-Spigot-1366]
        ... 14 more

**Comment by dumptruckman** [comment]
Updated to latest dev builds.
