### ISSUE TITLE
Error when creating a portal

### ISSUE THREAD

**Issue by BerryTheGreat** [Multiverse/Multiverse-Portals#357]
01.01 11:52:15 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-"606148f"]
01.01 11:52:15 [Server] INFO at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:317) ~[?:?]
01.01 11:52:15 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
01.01 11:52:15 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
01.01 11:52:15 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
01.01 11:52:15 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
01.01 11:52:15 [Server] INFO at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
01.01 11:52:15 [Server] INFO at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:169) ~[?:?]
01.01 11:52:15 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;
01.01 11:52:15 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
01.01 11:52:15 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:528) [spigot.jar:git-Spigot-"606148f"]
01.01 11:52:15 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:625) [spigot.jar:git-Spigot-"606148f"]
01.01 11:52:15 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-"606148f"]
01.01 11:52:15 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:684) [spigot.jar:git-Spigot-"606148f"]
01.01 11:52:15 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_65]
01.01 11:52:15 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_65]
01.01 11:52:15 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-"606148f"]
01.01 11:52:15 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-"606148f"]
01.01 11:52:15 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-"606148f"]
01.01 11:52:15 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:940) [spigot.jar:git-Spigot-"606148f"]
01.01 11:52:15 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1105) [spigot.jar:git-Spigot-"606148f"]
01.01 11:52:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:643) ~[spigot.jar:git-Spigot-"606148f"]
01.01 11:52:15 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-"606148f"]
01.01 11:52:15 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-"606148f"]
01.01 11:52:15 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.4-b548
01.01 11:52:15 [Server] ERROR null
Error when I try to create a server

**Comment by TWSSYesterday** [comment]
Currently supports 5.x worldedit.

**Comment by Ironic8b498** [comment]
I have the same issue and from TWSSYesterday's comment I was able to create a portal manually. Since I'm running Worldedit 6.0 and have to run it for other plugins, I just copied and pasted a portal in the portals.yml file and edited with correct cords and changed portal name and destination worked great.
