### ISSUE TITLE
Creating a portal doesn't work

### ISSUE THREAD

**Issue by ZeTaurin** [Multiverse/Multiverse-Portals#365]
Here's the error when trying to create a portal

[23:37:57 INFO]: Blue issued server command: /mvp create City-World W
orld-City
[23:37:57 INFO]: WEAPI
[23:37:57 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvp'
 in plugin Multiverse-Portals v2.5-b713
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spi
got.jar:git-Spigot-899f5ee-1092acb]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
1) ~[spigot.jar:git-Spigot-899f5ee-1092acb]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServe
r.java:645) ~[spigot.jar:git-Spigot-899f5ee-1092acb]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerCon
nection.java:1115) [spigot.jar:git-Spigot-899f5ee-1092acb]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java
:950) [spigot.jar:git-Spigot-899f5ee-1092acb]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java
:26) [spigot.jar:git-Spigot-899f5ee-1092acb]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java
:53) [spigot.jar:git-Spigot-899f5ee-1092acb]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spi
got.jar:git-Spigot-899f5ee-1092acb]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_25]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_25]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:6
83) [spigot.jar:git-Spigot-899f5ee-1092acb]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:3
16) [spigot.jar:git-Spigot-899f5ee-1092acb]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:6
23) [spigot.jar:git-Spigot-899f5ee-1092acb]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java
:526) [spigot.jar:git-Spigot-899f5ee-1092acb]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSele
ctionWorld()Lcom/sk89q/worldedit/LocalWorld;
        at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedReg
ion(PortalPlayerSession.java:168) ~[?:?]
        at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(
CreateCommand.java:56) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRu
nCommand(CommandHandler.java:279) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFou
ndCommands(CommandHandler.java:143) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndR
unCommand(CommandHandler.java:93) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndR
unCommand(CommandHandler.java:71) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(Multiv
ersePortals.java:336) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spi
got.jar:git-Spigot-899f5ee-1092acb]
        ... 14 more
>

**Comment by LavaGaming** [comment]
I have the same problem :/

**Comment by LavaGaming** [comment]
I just found this: 
https://github.com/dmulloy2/Multiverse-Portals/releases
It's Multiverse Portals with the new WorldEdit API attached onto it. :)
