### ISSUE TITLE
Error in console when stepping into portal

### ISSUE THREAD

**Issue by celeris** [Multiverse/Multiverse-Portals#372]
Hello,

I installer MV portals on my server, but i keep getting this error when stepping into a portal:

[00:15:07 ERROR]: Could not pass event PlayerMoveEvent to Multiverse-Portals v2
4-b548
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.j
va:305) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.ja
a:62) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.
ava:502) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.
ava:487) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.jav
:255) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PacketPlayInFlying.a(SourceFile:126) [s
igot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PacketPlayInPosition.a(SourceFile:57) [
pigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [sp
got-1.8.jar:git-Spigot-35348a5-ee6d0fa]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
?:1.8.0_31]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_31]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:
96) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:
16) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:
34) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.jav
:537) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.Multive
seCore.getBank()Lcom/fernferret/allpay/multiverse/GenericBank;
        at com.onarandombox.MultiversePortals.listeners.MVPPlayerListener.playe
Move(MVPPlayerListener.java:240) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:
.8.0_31]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.j
va:301) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
        ... 14 more
>

can someone please help me out?

Thanks in advance!

**Comment by Solistika** [comment]
Can confirm an issue.
http://hastebin.com/ilalasobug.avrasm

**Comment by darkmage4** [comment]
Same exact thing no matter what I do. :/

**Comment by TWSSYesterday** [comment]
Still occurs? We're on 2.5 now btw.

**Comment by Asuza** [comment]
I don't know if it's the exact same root cause, but I'm having the same issue every time I step into a portal, which causes the portal to not do anything.

```
[08:56:45 ERROR]: Could not pass event PlayerMoveEvent to Multiverse-Portals v2.4-b548
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-fdc1440-880a532]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-fdc1440-880a532]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-fdc1440-880a532]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-fdc1440-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270) [spigot-1.8.8.jar:git-Spigot-fdc1440-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot-1.8.8.jar:git-Spigot-fdc1440-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot-1.8.8.jar:git-Spigot-fdc1440-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-fdc1440-880a532]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-fdc1440-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-1.8.8.jar:git-Spigot-fdc1440-880a532]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-fdc1440-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8.jar:git-Spigot-fdc1440-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8.jar:git-Spigot-fdc1440-880a532]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.MultiverseCore.getBank()Lcom/fernferret/allpay/multiverse/GenericBank;
        at com.onarandombox.MultiversePortals.listeners.MVPPlayerListener.playerMove(MVPPlayerListener.java:240) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-fdc1440-880a532]
        ... 15 more
```

Output from `mv version -p` is here: http://j.mp/1Ts3fcm

Installed plugins are: DeathChest, Multiverse-Core, Backpacks, Multiverse-Portals

**Comment by TWSSYesterday** [comment]
Please try the latest dev build. http://ci.onarandombox.com/job/Multiverse-Portals/lastSuccessfulBuild/artifact/target/Multiverse-Portals-2.5.jar

**Comment by Solistika** [comment]
I just ended up having my developers make a very simple multi-world portal
plugin that takes care of teleporting on my server. Hope this patch works
though for those who are having this error.

**Comment by dumptruckman** [comment]
You need to update to the latest dev version of both Core and Portals if you're going to use the latest dev of either. http://ci.onarandombox.com/
