### ISSUE TITLE
Entering Portal does not work with latest MV Portal

### ISSUE THREAD

**Issue by infect** [Multiverse/Multiverse-Portals#389]
As soon as i enter the portal, this error pops up.

Running latest Spigot 1.8.7 and latest DevBuild from Multiverse-Core and Multiverse-Portal

[03:35:39 ERROR]: Could not pass event PlayerMoveEvent to Multiverse-Portals v2.5-b723
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-6d16e64-3e9b5c9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-6d16e64-3e9b5c9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-6d16e64-3e9b5c9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-6d16e64-3e9b5c9]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:269) [spigot.jar:git-Spigot-6d16e64-3e9b5c9]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-6d16e64-3e9b5c9]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:8) [spigot.jar:git-Spigot-6d16e64-3e9b5c9]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-6d16e64-3e9b5c9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-6d16e64-3e9b5c9]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-6d16e64-3e9b5c9]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-6d16e64-3e9b5c9]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-6d16e64-3e9b5c9]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-6d16e64-3e9b5c9]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.MultiverseCore.getEconomist()Lcom/onarandombox/MultiverseCore/utils/MVEconomist;
        at com.onarandombox.MultiversePortals.listeners.MVPPlayerMoveListener.playerMove(MVPPlayerMoveListener.java:105) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-6d16e64-3e9b5c9]
        ... 15 more

**Comment by dumptruckman** [comment]
Update to latest MV Core also.
