### ISSUE TITLE
Multiverse Portals Latest Build Error [ after creating portal ]

### ISSUE THREAD

**Issue by PinoyLifeCraft** [Multiverse/Multiverse-Portals#402]
After creating an portal in latest build of Multiverse Portals b7+
I receive an Error when testing to Enter -.- !!!!!
Here : 
[01:46:38 ERROR]: Could not pass event PlayerMoveEvent to Multiverse-Portals v2.
5-b723
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:297) ~[craftbukkit.jar:git-Bukkit-0a645a2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[craftbukkit.jar:git-Bukkit-0a645a2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:501) [craftbukkit.jar:git-Bukkit-0a645a2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:486) [craftbukkit.jar:git-Bukkit-0a645a2]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java
:257) [craftbukkit.jar:git-Bukkit-0a645a2]
        at net.minecraft.server.v1_8_R2.PacketPlayInFlying.a(SourceFile:126) [cr
aftbukkit.jar:git-Bukkit-0a645a2]
        at net.minecraft.server.v1_8_R2.PacketPlayInFlying$PacketPlayInPosition.
a(SourceFile:57) [craftbukkit.jar:git-Bukkit-0a645a2]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:1
3) [craftbukkit.jar:git-Bukkit-0a645a2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_60]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [craftbukki
t.jar:git-Bukkit-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:6
70) [craftbukkit.jar:git-Bukkit-0a645a2]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:3
36) [craftbukkit.jar:git-Bukkit-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:6
26) [craftbukkit.jar:git-Bukkit-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java
:534) [craftbukkit.jar:git-Bukkit-0a645a2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.Multiver
seCore.getEconomist()Lcom/onarandombox/MultiverseCore/utils/MVEconomist;
        at com.onarandombox.MultiversePortals.listeners.MVPPlayerMoveListener.pl
ayerMove(MVPPlayerMoveListener.java:105) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_60]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:295) ~[craftbukkit.jar:git-Bukkit-0a645a2]
        ... 15 more

**Comment by apesgrapes** [comment]
update multiverse-core to the latest dev build (#697). this fixed it for me.

**Comment by PinoyLifeCraft** [comment]
I use dev build (#697) multiverse core but it doesn't work!
:disappointed: how can you do that?

**Comment by Rigby90** [comment]
Caused by: java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.Multiver
seCore.getEconomist()

@PinoyLifeCraft Have you tried Multiverse-Core b699 and Multiverse-Portals b725 together?

http://ci.onarandombox.com/job/Multiverse-Core/699/
http://ci.onarandombox.com/job/Multiverse-Portals/725/
