### ISSUE TITLE
portals not creating

### ISSUE THREAD

**Issue by ravenfallls** [Multiverse/Multiverse-Portals#404]
not 100% why but everytime i try to create a portal i get this.

[19:07:29] [Server thread/INFO]: ravenfalls issued server command: /mvpc east e:atharland,2400,90,0
[19:07:29] [Server thread/INFO]: WEAPI
[19:07:29] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvpc' in plugin Multiverse-Portals v2.4-b548
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Bukkit-62a2169]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit.jar:git-Bukkit-62a2169]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:620) ~[craftbukkit.jar:git-Bukkit-62a2169]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1106) [craftbukkit.jar:git-Bukkit-62a2169]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:966) [craftbukkit.jar:git-Bukkit-62a2169]
	at net.aufdemrand.denizen.utilities.packets.intercept.AbstractListenerPlayIn.a(AbstractListenerPlayIn.java:87) [denizen-0.9.7-SNAPSHOT.jar:?]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37) [craftbukkit.jar:git-Bukkit-62a2169]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9) [craftbukkit.jar:git-Bukkit-62a2169]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Bukkit-62a2169]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-Bukkit-62a2169]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:673) [craftbukkit.jar:git-Bukkit-62a2169]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit.jar:git-Bukkit-62a2169]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [craftbukkit.jar:git-Bukkit-62a2169]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [craftbukkit.jar:git-Bukkit-62a2169]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;
	at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:169) ~[?:?]
	at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
	at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:317) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Bukkit-62a2169]
	... 16 more
[19:08:34] [Server thread/INFO]: ravenfalls lost connection: Disconnected
[19:08:34] [Server thread/INFO]: ravenfalls left the game.

**Comment by Rigby90** [comment]
[code]Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;[/code]

Have you recently changed your WorldEdit version?

**Comment by dumptruckman** [comment]
This issue is directly related to a version incompatibility with WorldEdit and MV-Portals. If you are using WorldEdit 6 you need to update to the latest betas of MV-Core and MV-Portals on dev.bukkit.org.
