### ISSUE TITLE
Portal wont TP

### ISSUE THREAD

**Issue by EJK07** [Multiverse/Multiverse-Portals#416]
Console view after each attempt to use a portal

 [09:48:56] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Multiverse-Portals v2.4-b548org.bukkit.event.EventExceptionat org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[CraftBukkit188.jar:git-Bukkit-d3e0b6f]at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[CraftBukkit188.jar:git-Bukkit-d3e0b6f]at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [CraftBukkit188.jar:git-Bukkit-d3e0b6f]at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [CraftBukkit188.jar:git-Bukkit-d3e0b6f]at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:257) [CraftBukkit188.jar:git-Bukkit-d3e0b6f]at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [CraftBukkit188.jar:git-Bukkit-d3e0b6f]at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [CraftBukkit188.jar:git-Bukkit-d3e0b6f]at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [CraftBukkit188.jar:git-Bukkit-d3e0b6f]at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_80]at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_80]at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [CraftBukkit188.jar:git-Bukkit-d3e0b6f]at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:673) [CraftBukkit188.jar:git-Bukkit-d3e0b6f]at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [CraftBukkit188.jar:git-Bukkit-d3e0b6f]at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [CraftBukkit188.jar:git-Bukkit-d3e0b6f]at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [CraftBukkit188.jar:git-Bukkit-d3e0b6f]at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]Caused by: java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.MultiverseCore.getBank()Lcom/fernferret/allpay/multiverse/GenericBank;at com.onarandombox.MultiversePortals.listeners.MVPPlayerListener.playerMove(MVPPlayerListener.java:240) ~[?:?]at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source) ~[?:?]at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_80]at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_80]at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[CraftBukkit188.jar:git-Bukkit-d3e0b6f]... 15 more

i had to disable world edit to use MVP's own wand. both portals successfully created as a 1 way trip
keep getting above issue when trying to use/pass through the portal

any tips here to fix this issue??

**Comment by dumptruckman** [comment]
Use the latest beta builds at the very least. The build you're using is like 3 years old or something. We do not support 2.4 anymore.

**Comment by EJK07** [comment]
ok thx
