### ISSUE TITLE
Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.5-b699

### ISSUE THREAD

**Issue by RocoWayne** [Multiverse/Multiverse-Portals#418]
Im having this error in the logs when i try to create a new portal (my other portals works just fine)

```
[10:31:23] [Server thread/INFO]: Rokito issued server command: /mvp create ntocreative Creativo
[10:31:23] [Server thread/INFO]: WEAPI
[10:31:23] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.5-b699
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;
	at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:168) ~[?:?]
	at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
	at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:336) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
	... 15 more
```

**Comment by FernFerret** [comment]
Looks like a world edit incompatibility at first glance, update: world edit, multiverse portals and multiverse core

**Comment by RocoWayne** [comment]
Interesting idea. I will update Worledit first. thanks

**Comment by FernFerret** [comment]
Your MV versions are also out of date, update those too.

**Comment by FernFerret** [comment]
Closing as inactive (> 7 days without comment from submitter) and we're trying to keep up with unattended issues better.

If you're still having issues, please post an update and we'll reopen this!  :+1:
