### ISSUE TITLE
can not create any portals

### ISSUE THREAD

**Issue by hambobolubia** [Multiverse/Multiverse-Portals#422]
like the title says i cant create and new portals i get an error ive tried everything i can think of, useing the beta builds, uninstalled world edit, nothing seems to fix it
heres my console log for when the error happens

`[01:28:24 INFO]: hambobolubia1 issued server command: /mvpc test

org.bukkit.command.CommandException: Unhandled exception executing command 'mvpc
' in plugin Multiverse-Portals v2.5-bUNKNOWN
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spi
got-1.9.jar:git-Spigot-90839e6-0ff499c]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
1) ~[spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServe
r.java:645) ~[spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerCon
nection.java:1350) [spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java
:1185) [spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java
:45) [spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java
:1) [spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:1
3) [spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_60]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9
.jar:git-Spigot-90839e6-0ff499c]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:7
21) [spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:4
00) [spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:6
60) [spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java
:559) [spigot-1.9.jar:git-Spigot-90839e6-0ff499c]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lor
g/bukkit/entity/Player;
        at com.onarandombox.MultiversePortals.MVPortal.addToUpperLists(MVPortal.
java:174) ~[?:?]
        at com.onarandombox.MultiversePortals.MVPortal.init(MVPortal.java:101) ~
[?:?]
        at com.onarandombox.MultiversePortals.MVPortal.<init>(MVPortal.java:63)
~[?:?]
        at com.onarandombox.MultiversePortals.MVPortal.<init>(MVPortal.java:236)
 ~[?:?]
        at com.onarandombox.MultiversePortals.utils.PortalManager.addPortal(Port
alManager.java:126) ~[?:?]
        at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(
CreateCommand.java:62) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRu
nCommand(CommandHandler.java:279) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFou
ndCommands(CommandHandler.java:143) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndR
unCommand(CommandHandler.java:93) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndR
unCommand(CommandHandler.java:71) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(Multiv
ersePortals.java:348) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spi
got-1.9.jar:git-Spigot-90839e6-0ff499c]
        ... 15 more
[01:28:32 INFO]: [skyworld]<hambobolubia1> test

> `

 please help thanks

**Comment by Xinoms** [comment]
When you do the command in game does it show the same as it shows me (see attached image)?

If you get the same, I have the exact same problem and have no clue how to change it, I would also be very grateful to know how to sort the issue.

<img width="978" alt="screen shot 2016-04-09 at 22 49 28" src="https://cloud.githubusercontent.com/assets/18371191/14406647/66ecad32-fea5-11e5-8a45-f90e67d9009d.png">

**Comment by Xinoms** [comment]
Check this link, it might help you, I'm going to try it my self now. :)

https://github.com/Multiverse/Multiverse-Portals/issues/392

**Comment by Xinoms** [comment]
I've updated both core and portal to the latest version by going to this like and it's now working. :)
Hope it works for you.

**Comment by Tzzzt123** [comment]
Dont do /mvpc test! do /mvp debug <portalname>
If you want to make a portal: type /mvp wand (If you use Worldedit type //wand)
Build a portal with anything around and choose both positions (pos1 leftclick; pos2 rightclick)
You can also fill the portal with water or lava afterwoods!
Regards Tzzzt123
