### ISSUE TITLE
Error on portal create (Multiverse-Portals & Worldedit conflict?)

### ISSUE THREAD

**Issue by skruidenier** [Multiverse/Multiverse-Portals#429]
Hi,
When i try to create a new portal i get this error in-game:
![error](https://cloud.githubusercontent.com/assets/7668514/14829509/23aa3ad6-0bec-11e6-98e2-e003869b07d5.png)
In the console i see this error:

```
INFO]: skruidenier issued server command: /mvp create failparkour6 p:parkour6lobby
[20:13:07 INFO]: WEAPI
[20:13:07 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.4-b548
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Custom.jar:git-Spigot-f928e7a-e91aed8]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Custom.jar:git-Spigot-f928e7a-e91aed8]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[Custom.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [Custom.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [Custom.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [Custom.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [Custom.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Custom.jar:git-Spigot-f928e7a-e91aed8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_99]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_99]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [Custom.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [Custom.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [Custom.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [Custom.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [Custom.jar:git-Spigot-f928e7a-e91aed8]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_99]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;
        at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:169) ~[?:?]
        at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:317) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Custom.jar:git-Spigot-f928e7a-e91aed8]
        ... 15 more
```

**I'm using:
- Spigot 1.8.7
- Multiverse-Core 2.4
- Multiverse-Portals 2.4
- Worldedit 6.1 (i also tried version 6.0 which gives the same error)**

**Comment by bamboy12** [comment]
same

**Comment by bamboy12** [comment]
https://ci.onarandombox.com/job/Multiverse-Portals/ DOWNLOAD FROM HERE

**Comment by FernFerret** [comment]
@bamboy12 is correct, do we have a 2.4 version posted somewhere? 2.5 is what everyone should be using (from the ci).

I presume the new version worked for your @bamboy12? What about you @skruidenier ?

**Comment by dabates** [comment]
this also worked for me!  thanks for that.. somehow I had also gotten the 2.4 version
