### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by BlitzProGaming** [Multiverse/Multiverse-Portals#441]
[19:35:36 INFO]: BlitzProGaming issued server command: /mvp create Hub_Skywars Skywars

org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Por
tals v1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-d20369
f-7fc5cd8]
        at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98) ~[?:?]

```
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:
```

git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigo
t.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot.jar:git-Sp
igot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spig
ot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigo
t-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot
-d20369f-7fc5cd8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-d20369f-7fc5c
d8]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigo
t-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigo
t-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigo
t-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spi
got-d20369f-7fc5cd8]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at com.onarandombox.MultiversePortals.MVPortal.addToUpperLists(MVPortal.java:174) ~[?:?]
        at com.onarandombox.MultiversePortals.MVPortal.init(MVPortal.java:101) ~[?:?]
        at com.onarandombox.MultiversePortals.MVPortal.<init>(MVPortal.java:63) ~[?:?]
        at com.onarandombox.MultiversePortals.MVPortal.<init>(MVPortal.java:236) ~[?:?]
        at com.onarandombox.MultiversePortals.utils.PortalManager.addPortal(PortalManager.java:126) ~[?:?
]
        at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:62) ~[
?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.j
ava:279) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler
.java:143) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.
java:93) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.
java:71) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:345) ~[?
:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-d20369
f-7fc5cd8]
        ... 15 more

**Comment by BlitzProGaming** [comment]
Replies with "An internal error occurred while attempting to execute this command"

I am using World Edit 6.1

Multiverse-core 2.4 for minecraft 1.9 spigot

Using PermissionsEX 1.23.4

**Comment by Jadiction** [comment]
Closing ticket because it's years old. Update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists.
