### ISSUE TITLE
Minecraft 1.11.2 - Not WorldEdit Issues - Inter Error

### ISSUE THREAD

**Issue by fbepyon** [Multiverse/Multiverse-Portals#451]
Hello,

So I recently setup my server with sipgot version 1.11.2, and keep getting "Internal Error" on Multiverse-Portals.

I removed WorldEditor because others said this was causing the issues which is not the case here, because even removing it I still get the same error.

Is there is possible way this can be corrected for version 1.11.2

Here is my log 

`[07:54:23] [Server thread/INFO]: fbepyon issued server command: /mvp wand
[07:54:42] [Server thread/INFO]: fbepyon issued server command: /mvpc dungeon
[07:54:42] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvpc' in plugin Multiverse-Portals v2.5-bUNKNOWN
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_95]
at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_95]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
at com.onarandombox.MultiversePortals.MVPortal.addToUpperLists(MVPortal.java:174) ~[?:?]
at com.onarandombox.MultiversePortals.MVPortal.init(MVPortal.java:101) ~[?:?]
at com.onarandombox.MultiversePortals.MVPortal.<init>(MVPortal.java:63) ~[?:?]
at com.onarandombox.MultiversePortals.MVPortal.<init>(MVPortal.java:236) ~[?:?]
at com.onarandombox.MultiversePortals.utils.PortalManager.addPortal(PortalManager.java:126) ~[?:?]
at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:62) ~[?:?]
at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:348) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
... 15 more`

**Comment by Scindix** [comment]
I've got the exact same issue.

**Comment by Scindix** [comment]
And I solved the problem by rebuilding Multiverse-Portals from source.

**Comment by dumptruckman** [comment]
Update to a non dinosaur aged build... like the latest beta or dev builds
