### ISSUE TITLE
Does not load on 1.12 with this error

### ISSUE THREAD

**Issue by manmadehuman** [Multiverse/Multiverse-Portals#459]
Multiverse works still with 1.12, no issues. Just portals won't load

`ERROR 06/30/2017 17:32:26
17:32:26Error occurred while enabling Multiverse-Portals v2.5.0-SNAPSHOT-b748 (Is it up to date?)
Console 06/30/2017 17:32:26
17:32:26java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
at com.onarandombox.MultiversePortals.MultiversePortals.loadConfig(MultiversePortals.java:245) ~[?:?]
at com.onarandombox.MultiversePortals.MultiversePortals.onEnable(MultiversePortals.java:132) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-7228328-d603539]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-7228328-d603539]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-7228328-d603539]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-7228328-d603539]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-7228328-d603539]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-7228328-d603539]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-7228328-d603539]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-7228328-d603539]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-7228328-d603539]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-7228328-d603539]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]`

**Comment by manmadehuman** [comment]
2.5.1 snapshop fixes the issue. I thought 2.5.0 was latest .
