### ISSUE TITLE
Not Behaving with WorldEdit

### ISSUE THREAD

**Issue by cogito808** [Multiverse/Multiverse-Portals#475]
Spigot 1.13 with new worlds (not converted)
worldedit-bukkit-7.0.0-SNAPSHOT-dist
Multiverse-Portals-2.5.2-SNAPSHOT
They both work well independently of each other, and WorldEdit functions with Portals, but Portals does not work with Worldedit running.

[20:37:36 INFO]: [Multiverse-Portals] Enabling Multiverse-Portals v2.5.2-SNAPSHOT-b765
[20:37:36 INFO]: [Multiverse-Portals] - Version 2.5.2-SNAPSHOT-b765 Enabled - By Rigby and fernferret
[20:37:36 INFO]: [MVPLogging] 0 - Portals(s) loaded
[20:37:36 ERROR]: Error occurred while enabling Multiverse-Portals v2.5.2-SNAPSHOT-b765 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/bukkit/WorldEditAPI
        at com.onarandombox.MultiversePortals.WorldEditConnection.connect(WorldEditConnection.java:47) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.checkForWorldEdit(MultiversePortals.java:174) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onEnable(MultiversePortals.java:141) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.jar:git-Spigot-69774b3-e3c21de]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.jar:git-Spigot-69774b3-e3c21de]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.jar:git-Spigot-69774b3-e3c21de]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:425) [spigot-1.13.jar:git-Spigot-69774b3-e3c21de]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:339) [spigot-1.13.jar:git-Spigot-69774b3-e3c21de]
        at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot-1.13.jar:git-Spigot-69774b3-e3c21de]
        at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot-1.13.jar:git-Spigot-69774b3-e3c21de]
        at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot-1.13.jar:git-Spigot-69774b3-e3c21de]
        at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13.jar:git-Spigot-69774b3-e3c21de]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot-1.13.jar:git-Spigot-69774b3-e3c21de]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.bukkit.WorldEditAPI
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.jar:git-Spigot-69774b3-e3c21de]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.jar:git-Spigot-69774b3-e3c21de]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        ... 14 more

**Comment by limegreenicy** [comment]
I think I have the same or a similar issue. I can get the /mvp wand thing, though when trying to create a portal it says an internal error occurred in the chat.

**Comment by limegreenicy** [comment]
Using world edit *

**Comment by Bobbbe** [comment]
i have the same issue.  wait for the update :) be patient this will be soon i guess.

**Comment by lifehome** [comment]
The build at #488 have fixed the integration between MVPortals and latest Worldedit, this is primarily due to WE have introduced a thing called `BlockVector3` in replacing the old Vector type.

**Comment by Jadiction** [comment]
Please update to the latest Multiverse-Portals (and WorldEdit). They both should work.
