### ISSUE TITLE
Wand Tool broken in 2.5+

### ISSUE THREAD

**Issue by excedra** [Multiverse/Multiverse-Portals#484]
Hello,

when using /mvp wand the attached error.

I've tried different Versions (Multiverse Core 2.6, 2.5.2) and same Versions for Portals and NetherPortals. Also tried mixing them up. Wand seems not to work.

I am using CraftBukkit version git-Spigot-f6a273b-cd6252a (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT).

`[Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.5.1-b760
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-f6a273b-cd6252a]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-f6a273b-cd6252a]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot.jar:git-Spigot-f6a273b-cd6252a]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646) ~[spigot.jar:git-Spigot-f6a273b-cd6252a]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot.jar:git-Spigot-f6a273b-cd6252a]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Spigot-f6a273b-cd6252a]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-f6a273b-cd6252a]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-f6a273b-cd6252a]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-f6a273b-cd6252a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot.jar:git-Spigot-f6a273b-cd6252a]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-f6a273b-cd6252a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-f6a273b-cd6252a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-f6a273b-cd6252a]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.ItemStack.<init>(II)V
        at com.onarandombox.MultiversePortals.commands.WandCommand.runCommand(WandCommand.java:59) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:358) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-f6a273b-cd6252a]
        ... 15 more
`

**Comment by VictorioBerra** [comment]
Same issue. I am using the latest CI build of WorldEdit.

**Comment by lifehome** [comment]
Have you tried the build at #488? Also if you have MVPortals installed, MVNetherPortal is (kinda, depends on your need) not needed to be there anymore.

**Comment by OragonEfreet** [comment]
Hello,

I have the same issue and I tried with the latest build as today (build 788 on Jenkins).

Minecraft version 1.13.2

My list of plugins:
- LuckPerms
- ChatControl
- Gringgots
- Vault
- MassiveCore
- Multiverse-Core (here also, latest build)
- Factions
- Shopkeepers
- Multiverse-Portals
- DiscordSRV
- Multiverse-Inventories

The bug already appeared when I had *only* MV-Core and MV-Portals installer.

Reproduction:

Ingame, i type `/mvp wand`.

Result:
The ingame chat inputs: "An internal error occurred while attempting to perform this command".

Log:
```
[16:07:07] [Server thread/INFO]: Oragon_Efreet issued server command: /mvp wand
[16:07:07] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v3.0.0-SNAPSHOT-b788
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils$$Lambda$2094.000000001186AB70.run(Unknown Source) ~[?:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_192]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_192]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]
Caused by: java.lang.NullPointerException
at com.onarandombox.MultiversePortals.commands.WandCommand.runCommand(WandCommand.java:53) ~[?:?]
at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:372) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
... 16 more
```

**Comment by OragonEfreet** [comment]
Haven't noticed but at server startup there's also an error:

```
...
[Multiverse-Core] 5 - World(s) loaded.
[Multiverse-Core] Version 3.0.0-SNAPSHOT-b760 (API v22) Enabled - By Rigby, fernferret, lithium3141, main-- and dumptruckman
...
[Multiverse-Portals] Enabling Multiverse-Portals v3.0.0-SNAPSHOT-b788
[Multiverse-Portals] - Version 3.0.0-SNAPSHOT-b788 Enabled - By Rigby and fernferret
[MVPLogging] 0 - Portals(s) loaded
[16:12:41] [Server thread/ERROR]: Error occurred while enabling Multiverse-Portals v3.0.0-SNAPSHOT-b788 (Is it up to date?)
java.lang.NoClassDefFoundError: com.sk89q.worldedit.session.SessionOwner
at com.onarandombox.MultiversePortals.MultiversePortals.checkForWorldEdit(MultiversePortals.java:178) ~[?:?]
at com.onarandombox.MultiversePortals.MultiversePortals.onEnable(MultiversePortals.java:147) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.session.SessionOwner
at java.net.URLClassLoader.findClass(URLClassLoader.java:592) ~[?:1.8.0_192]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-3cb9dcb-77ca7ca]
at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:934) ~[?:1.8.0_192]
at java.lang.ClassLoader.loadClass(ClassLoader.java:879) ~[?:1.8.0_192]
at java.lang.ClassLoader.loadClass(ClassLoader.java:862) ~[?:1.8.0_192]
... 13 more
...
[Multiverse-Inventories] Enabling Multiverse-Inventories v3.0.0-SNAPSHOT-b452
...
[Multiverse-Inventories 3.0.0-SNAPSHOT-b452] enabled.
```

**Comment by dumptruckman** [comment]
Update WorldEdit.

**Comment by OragonEfreet** [comment]
I don't have WorldEdit.

**Comment by dumptruckman** [comment]
Thanks. I honestly have no idea how this has never been fixed before. The latest dev build should work without WorldEdit now.

**Comment by VictorioBerra** [comment]
I think because the issues aren't being monitored very well.

**Comment by dumptruckman** [comment]
Oh I'm very aware of that. My comment was more about how this has never been fixed despite it being an issue basically since the inception of this plugin.

**Comment by OragonEfreet** [comment]
It works like a charm. Thank you!
