### ISSUE TITLE
spigot 1.13.2  Error with portals.  

### ISSUE THREAD

**Issue by FootrottFlats** [Multiverse/Multiverse-Portals#487]
[21:09:43 INFO]: [Multiverse-Core] Enabling Multiverse-Core v2.5.0-b727
[21:09:43 INFO]: [Multiverse-Core] Loading World & Settings - 'BSkyBlock_world' - Env: NORMAL - Type: FLAT & seed: -239635215969594840
[21:09:43 WARN]: [Multiverse-Core] Spawn location from world.dat file was unsafe. Adjusting...
[21:09:43 WARN]: [Multiverse-Core] Original Location: X: -168 Y: 64 Z: 232 P: 0 Y: 0
[21:09:49 ERROR]: [Multiverse-Core] Safe spawn NOT found!!!
[21:09:49 INFO]: [Multiverse-Core] Loading World & Settings - 'BSkyBlock_world_nether' - Env: NETHER - Type: FLAT & seed: 4435563141271555208
[21:09:49 WARN]: [Multiverse-Core] Spawn location from world.dat file was unsafe. Adjusting...
[21:09:49 WARN]: [Multiverse-Core] Original Location: X: 0 Y: 64 Z: 0 P: 0 Y: 0
[21:09:54 ERROR]: [Multiverse-Core] Safe spawn NOT found!!!
[21:09:55 INFO]: [Multiverse-Core] Loading World & Settings - 'BSkyBlock_world_the_end' - Env: THE_END - Type: FLAT & seed: 1454664206191786084
[21:09:55 WARN]: [Multiverse-Core] Spawn location from world.dat file was unsafe. Adjusting...
[21:09:55 WARN]: [Multiverse-Core] Original Location: X: 0 Y: 64 Z: 0 P: 0 Y: 0
[21:10:00 ERROR]: [Multiverse-Core] Safe spawn NOT found!!!
[21:10:00 INFO]: [Multiverse-Core] 6 - World(s) loaded.
[21:10:00 INFO]: [Multiverse-Core] Version 2.5.0-b727 (API v20) Enabled - By Rigby, fernferret, lithium3141, main-- and dumptruckman
[21:10:00 INFO]: [Multiverse-Portals] Enabling Multiverse-Portals v2.5-b725
[21:10:00 INFO]: [Multiverse-Portals] - Version 2.5-b725 Enabled - By Rigby and fernferret
[21:10:00 INFO]: [MVPLogging] 0 - Portals(s) loaded
[21:10:00 ERROR]: Error occurred while enabling Multiverse-Portals v2.5-b725 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
        at com.onarandombox.MultiversePortals.MultiversePortals.loadConfig(MultiversePortals.java:245) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onEnable(MultiversePortals.java:132) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:426) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:340) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[21:10:00 INFO]: [Multiverse-NetherPortals] Enabling Multiverse-NetherPortals v2.5-b675
[21:10:00 INFO]: [Multiverse-NetherPortals] - Version 2.5-b675 Enabled - By Rigby and fernferret

**Comment by Jadiction** [comment]
Update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists.
