### ISSUE TITLE
org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.5.0-b751

### ISSUE THREAD

**Issue by the-webguys** [Multiverse/Multiverse-Portals#489]
Hello, I am having this issue, I have done a little googling and see the issues seem to be related to World edit. Wll I am not running anything like that. I am running the following plugins:

- dynmap
- DragginEggDrop
- VeinMiner
- Multiverse_core
- ScubaHelmet
- Magic
- Multiverse-Portals

Any help is greatly appreciated :)

`[02:15:52 INFO]: dc_wan issued server command: /mvp wand
[02:15:52 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.5.0-b751
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.13.2.jar:git-Bukkit-a4c555b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:138) ~[craftbukkit-1.13.2.jar:git-Bukkit-a4c555b]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:682) ~[craftbukkit-1.13.2.jar:git-Bukkit-a4c555b]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1587) ~[craftbukkit-1.13.2.jar:git-Bukkit-a4c555b]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1447) ~[craftbukkit-1.13.2.jar:git-Bukkit-a4c555b]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(SourceFile:37) ~[craftbukkit-1.13.2.jar:git-Bukkit-a4c555b]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(SourceFile:9) ~[craftbukkit-1.13.2.jar:git-Bukkit-a4c555b]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[craftbukkit-1.13.2.jar:git-Bukkit-a4c555b]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [craftbukkit-1.13.2.jar:git-Bukkit-a4c555b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:843) [craftbukkit-1.13.2.jar:git-Bukkit-a4c555b]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:382) [craftbukkit-1.13.2.jar:git-Bukkit-a4c555b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:796) [craftbukkit-1.13.2.jar:git-Bukkit-a4c555b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:699) [craftbukkit-1.13.2.jar:git-Bukkit-a4c555b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.ItemStack.<init>(II)V
        at com.onarandombox.MultiversePortals.commands.WandCommand.runCommand(WandCommand.java:59) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:358) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.13.2.jar:git-Bukkit-a4c555b]`

**Comment by the-webguys** [comment]
hey, sorry for late reply. Been playing MC (you know how it is)
Version: Multiverse-Core Version: 2.5.0-b727
and no, I can't remember where i got the files from. I don't really understand the jenkings website, it's a little confusing

**Comment by lifehome** [comment]
Please try to obtain both MVCore and MVPortals using the following link, once you're on the page, look for the word `Last Successful Artifacts` in the middle, choose whatever ends in either `bukkit` or `.jar`, do not choose things named in `javadoc` or `sources` as they are built meant for developers.

(Direct links are given here)
MVCore: https://ci.onarandombox.com/job/Multiverse-Core/lastSuccessfulBuild/artifact/target/Multiverse-Core-2.6.0.jar
MVPortals: https://ci.onarandombox.com/view/Multiverse/job/Multiverse-Portals/lastSuccessfulBuild/artifact/target/Multiverse-Portals-2.5.2-SNAPSHOT.jar

However I do recommend try out the build at #488 if the builds above failed, as the jenkins is set to build against Spigot-API 1.12-R0.1.

**Comment by Jadiction** [comment]
Update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists.
