### ISSUE TITLE
ERROR Occurred while enabling Multiverse-Portalsv2.5.2-snapshot-b766

### ISSUE THREAD

**Issue by bonette** [Multiverse/Multiverse-Portals#490]
I searched for an answer with other Issues and downloaded the stable copies recommended to another User on this site (Issue #489).  However, I am receiving this error upon startup of the server.  It does not allow for the Wand to be used to create new portals, however, other /commands seem to work just fine.  
* Tried running with Worldedit/Guard and without, was unable to get it to function correctly.
* Removed ALL plugins except for Multiverse-Core and Portals.  Still received this error.
I hope this is helpful!

```
 [Server] ERROR Error occurred while enabling Multiverse-Portals v2.5.2-SNAPSHOT-b766 (Is it up to date?) 
 [Server] INFO java.lang.NoClassDefFoundError: com/sk89q/worldedit/IncompleteRegionException 
 [Server] INFO at com.onarandombox.MultiversePortals.MultiversePortals.checkForWorldEdit(MultiversePortals.java:172) ~[?:?] 
 [Server] INFO at com.onarandombox.MultiversePortals.MultiversePortals.onEnable(MultiversePortals.java:141) ~[?:?] 
 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b] 
 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b] 
 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b] 
 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b] 
 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b] 
 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:579) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b] 
 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:541) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b] 
 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:419) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b] 
 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b] 
 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b] 
 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191] 
 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.IncompleteRegionException 
 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191] 
 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b] 
 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
```

**Comment by bonette** [comment]
Just to be sure, I am also removing all folders associated with the worldedit plugins, since it's calling for the plugin right after the error.

**Comment by Kingdingbat** [comment]
I also have this issue. There is some kind of conflict between WorldEdit and Multiverse Portals. WorldEdit is a requirement for some of our other plugins so we must use it. Portals is not loading on server restart when WorldEdit is enabled.

**Comment by OpticFusion1** [comment]
@bonette  @Kingdingbat try with MY fork of the plugin https://www.spigotmc.org/members/optic_fusion1.391639/#resources you'll find all MV plugins in the given link, make sure you have worldedit

**Comment by OpticFusion1** [comment]
@dumptruckman after checking this on my own various times, things like this seems to be a WorldEdit & FAWE, which means you'll need to support both

**Comment by everydayplacebo** [comment]
I had a similar issue with a NoClassDefFoundError loading Portals with WorldEdit.
Loads fine without WorldEdit, which makes sense, considering it's complaining about the WorldEdit API


[06:41:24 INFO]: Loaded 0 recipes
[06:41:24 INFO]: Starting minecraft server version 1.13.2
[06:41:24 INFO]: Loading properties
[06:41:24 INFO]: Default game type: CREATIVE
[06:41:24 INFO]: Generating keypair
[06:41:25 INFO]: Starting Minecraft server on *:25565
[06:41:25 INFO]: Using epoll channel type
[06:41:25 INFO]: This server is running CraftBukkit version git-Bukkit-a2dd0e3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)



[06:38:18 INFO]: Preparing spawn area: 96%
[06:38:18 INFO]: Preparing spawn area: 100%
[06:38:18 INFO]: Time elapsed: 5295 ms
[06:38:18 INFO]: [WorldEdit] Enabling WorldEdit v7.0.0-beta-05;6bbf29b
[06:38:19 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_13_R2_2 as the Bukkit adapter
[06:38:20 INFO]: WEPIF: Using the Bukkit Permissions API.
[06:38:20 INFO]: [Multiverse-Core] Enabling Multiverse-Core v2.5.0-b727
[06:38:20 INFO]: [Multiverse-Core] 3 - World(s) loaded.
[06:38:20 INFO]: [Multiverse-Core] Version 2.5.0-b727 (API v20) Enabled - By Rigby, fernferret, lithium3141, main-- and dumptruckman
[06:38:20 INFO]: [Multiverse-Portals] Enabling Multiverse-Portals v2.5.0-b751
[06:38:20 INFO]: [Multiverse-Portals] - Version 2.5.0-b751 Enabled - By Rigby and fernferret
[06:38:20 INFO]: [MVPLogging] 0 - Portals(s) loaded
[06:38:20 ERROR]: Error occurred while enabling Multiverse-Portals v2.5.0-b751 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/bukkit/WorldEditAPI
        at com.onarandombox.MultiversePortals.WorldEditConnection.connect(WorldEditConnection.java:47) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.checkForWorldEdit(MultiversePortals.java:174) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onEnable(MultiversePortals.java:141) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[craftbukkit.jar:git-Bukkit-a2dd0e3]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit.jar:git-Bukkit-a2dd0e3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit.jar:git-Bukkit-a2dd0e3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:423) [craftbukkit.jar:git-Bukkit-a2dd0e3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:349) [craftbukkit.jar:git-Bukkit-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:571) [craftbukkit.jar:git-Bukkit-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:533) [craftbukkit.jar:git-Bukkit-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:411) [craftbukkit.jar:git-Bukkit-a2dd0e3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:270) [craftbukkit.jar:git-Bukkit-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:676) [craftbukkit.jar:git-Bukkit-a2dd0e3]
        at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.bukkit.WorldEditAPI
        at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134) ~[craftbukkit.jar:git-Bukkit-a2dd0e3]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[craftbukkit.jar:git-Bukkit-a2dd0e3]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:566) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:499) ~[?:?]
        ... 14 more

**Comment by everydayplacebo** [comment]
I know we didn't have the same NoClassDefFoundError, but it looks like an issue with WorldEdit compatibility for both of us.
This worked for me using current version of WorldEdit and Multiverse-Core, and whatever craftbukkit version buildtools downloads by default.

[https://github.com/Multiverse/Multiverse-Portals/pull/488](url)

**Comment by kanthos88tr** [comment]
To fix the above I was getting I did the following: 
I found the fix! 
I installed multiverse core 2.60
multiverse portals snapshot 2.52
world edit 7.0.0 beta

I didn't delete the folders just the .jar from plugins and then reset the server

**Comment by Jadiction** [comment]
Self-solved.
