### ISSUE TITLE
NoClassDefFoundError: com/onarandombox/MultiverseCore/utils/BlockSafety

### ISSUE THREAD

**Issue by Schneidertm** [Multiverse/Multiverse-Portals#492]
Multiverse-Portals: #767
Multiverse-Core: #746
git-Paper-509 (MC: 1.13.2) 

Players unable to teleport via portal.

```
[19:13:43] [Server thread/ERROR]: Could not pass event PlayerPortalEvent to Multiverse-Portals v2.5.2-SNAPSHOT-b773
java.lang.NoClassDefFoundError: com/onarandombox/MultiverseCore/utils/BlockSafety
	at com.onarandombox.MultiversePortals.destination.PortalDestination.getMinimumWith2Air(PortalDestination.java:74) ~[?:?]
	at com.onarandombox.MultiversePortals.destination.PortalDestination.getLocation(PortalDestination.java:58) ~[?:?]
	at com.onarandombox.MultiversePortals.listeners.MVPPlayerListener.playerPortal(MVPPlayerListener.java:250) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor193.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-509]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.PlayerList.changeDimension(PlayerList.java:794) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.EntityPlayer.a(EntityPlayer.java:707) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.Entity.postTick(Entity.java:381) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1550) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.World.g(World.java:1516) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.WorldServer.p_(WorldServer.java:621) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1289) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:598) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1099) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-509]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by dumptruckman** [comment]
Indeed. The latest MV-Core is too new and Multiverse-Portals is not yet compatible. I'm working on it but my time is limited!

**Comment by Jadiction** [comment]
Update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists.
