### ISSUE TITLE
Multiverse 3.0.0 Hookup Worldedit 7

### ISSUE THREAD

**Issue by Futschel** [Multiverse/Multiverse-Portals#495]
[19:47:27 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvpc' in plugin Multiverse-Portals v2.5.2-SNAPSHOT-bUNKNOWN
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.regions.Region.getMinimumPoint()Lcom/sk89q/worldedit/math/BlockVector3;
        at com.onarandombox.MultiversePortals.WorldEditConnection.getSelectionMinPoint(WorldEditConnection.java:118) ~[?:?]
        at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:166) ~[?:?]
        at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:358) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        ... 15 more

**Comment by Futschel** [comment]
Also on MVC 3.0.0

[19:51:09 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvpc' in plugin Multiverse-Portals v3.0.0-SNAPSHOT-b788
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.regions.Region.getMinimumPoint()Lcom/sk89q/worldedit/math/BlockVector3;
        at com.onarandombox.MultiversePortals.WorldEditConnection.getSelectionMinPoint(WorldEditConnection.java:118) ~[?:?]
        at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:166) ~[?:?]
        at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
        at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
        at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
        at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
        at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:372) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
        ... 15 more

**Comment by dumptruckman** [comment]
Are you sure you're running WE 7.0.0?

**Comment by Futschel** [comment]
> 
> 
> Are you sure you're running WE 7.0.0?

[21:42:58 INFO]: WorldEdit version (unknown)
[21:42:58 INFO]: https://github.com/sk89q/worldedit/
[21:42:58 INFO]: ----------- Platforms -----------
[21:42:58 INFO]: * Bukkit-Official (7.0.0-beta-01;8975469)
[21:42:58 INFO]: ----------- Capabilities -----------
[21:42:58 INFO]: GAME_HOOKS: Bukkit-Official
[21:42:58 INFO]: CONFIGURATION: Bukkit-Official
[21:42:58 INFO]: USER_COMMANDS: Bukkit-Official
[21:42:58 INFO]: PERMISSIONS: Bukkit-Official
[21:42:58 INFO]: WORLDEDIT_CUI: Bukkit-Official
[21:42:58 INFO]: WORLD_EDITING: Bukkit-Official

**Comment by Futschel** [comment]
After Updating to WE 7.0.0. Beta 5; WG 7.0.0. Beta 3 
MVP is working fine !
