### ISSUE TITLE
Issue related to Multiverse-core End and Nether portals causing server to crash

### ISSUE THREAD

**Issue by EchocallingEarth** [Multiverse/Multiverse-Portals#500]
We get the following errors every time we enter a Nether or End Portal, followed by our Server crashing immediately. Often either requiring a admin break the portal the player is in or if no one is on and self testing a player data reset. 

We have done a bunch of research and keep getting back to Multiverse. Which is odd yes but maybe it is at the heart of the problem. We did have MultiversePortals on our server and recently upgraded to Simple Portals as there were to many conflicts with FAWE/WE that prevented portal creation. When we removed it we assumed that it would be fine afterwards. However clearly we were wrong. After a long day of researching we find many of the suggestions point to a null issue with multiverse core. However we can not see this, if you do please assist - thank you.

1.13.2 Paper Server

Full error flow below -
[00:47:44 ERROR]: Could not pass event PlayerPortalEvent to LobbyAPI v3.7.82
org.bukkit.event.EventException: null
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.exec
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:7
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
at net.minecraft.server.v1_13_R2.PlayerList.changeDimension(PlayerList.j
at net.minecraft.server.v1_13_R2.EntityPlayer.a(EntityPlayer.java:707) ~
at net.minecraft.server.v1_13_R2.Entity.postTick(Entity.java:381) ~[patc
at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1569
at net.minecraft.server.v1_13_R2.World.g(World.java:1535) ~[patched_1.13
at net.minecraft.server.v1_13_R2.WorldServer.p_(WorldServer.java:621) ~[
at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1308) ~[p
at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.ja
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.jav
at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
Caused by: java.lang.IllegalArgumentException: Cannot use null location with nul
at com.google.common.base.Preconditions.checkArgument(Preconditions.java
at org.bukkit.event.player.PlayerMoveEvent.validateLocation(PlayerMoveEv
at org.bukkit.event.player.PlayerMoveEvent.setTo(PlayerMoveEvent.java:86
at me.zombie_striker.lobbyapi.Main.onTeleport(Main.java:465) ~[?:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.exec
... 16 more
[00:47:44 ERROR]: Could not pass event PlayerPortalEvent to Multiverse-Core v3.0
java.lang.NullPointerException: null
at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerPort
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventEx
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:67
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:7
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
at net.minecraft.server.v1_13_R2.PlayerList.changeDimension(PlayerList.j
at net.minecraft.server.v1_13_R2.EntityPlayer.a(EntityPlayer.java:707) ~
at net.minecraft.server.v1_13_R2.Entity.postTick(Entity.java:381) ~[patc
at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1569
at net.minecraft.server.v1_13_R2.World.g(World.java:1535) ~[patched_1.13
at net.minecraft.server.v1_13_R2.WorldServer.p_(WorldServer.java:621) ~[
at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1308) ~[p
at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.ja
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.jav
at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
[00:47:44 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_13_R2.ReportedException: Ticking player
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.jav
at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
Caused by: java.lang.NullPointerException
at org.bukkit.craftbukkit.v1_13_R2.CraftTravelAgent.findOrCreate(CraftTr
at net.minecraft.server.v1_13_R2.PlayerList.changeDimension(PlayerList.j
at net.minecraft.server.v1_13_R2.EntityPlayer.a(EntityPlayer.java:707) ~
at net.minecraft.server.v1_13_R2.Entity.postTick(Entity.java:381) ~[patc
at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1569
at net.minecraft.server.v1_13_R2.World.g(World.java:1535) ~[patched_1.13
at net.minecraft.server.v1_13_R2.WorldServer.p_(WorldServer.java:621) ~[
at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1308) ~[p
at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.ja
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:
... 4 more
[00:47:44 ERROR]: Cause of unexpected exception was
java.lang.NullPointerException: null
at org.bukkit.craftbukkit.v1_13_R2.CraftTravelAgent.findOrCreate(CraftTr
at net.minecraft.server.v1_13_R2.PlayerList.changeDimension(PlayerList.j
at net.minecraft.server.v1_13_R2.EntityPlayer.a(EntityPlayer.java:707) ~
at net.minecraft.server.v1_13_R2.Entity.postTick(Entity.java:381) ~[patc
at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1569
at net.minecraft.server.v1_13_R2.World.g(World.java:1535) ~[patched_1.13
at net.minecraft.server.v1_13_R2.WorldServer.p_(WorldServer.java:621) ~[
at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1308) ~[p
at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.ja
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.jav
at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
[00:47:44 ERROR]: Could not save crash report to ./crash-reports/crash-2019-03-1
java.io.FileNotFoundException: ./crash-reports/crash-2019-03-18_00.47.44-server.
at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_202]
at java.io.FileOutputStream.open(Unknown Source) ~[?:1.8.0_202]
at java.io.FileOutputStream.(Unknown Source) ~[?:1.8.0_202]
at java.io.FileOutputStream.(Unknown Source) ~[?:1.8.0_202]
at net.minecraft.server.v1_13_R2.CrashReport.a(CrashReport.java:181) ~[p
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.jav
at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]

**Comment by dumptruckman** [comment]
Looks like lobbyapi is doing weird things. I suspect that is the source of your problems. Next time, please make sure to include ALL of the text in the errors. Every line appears to be truncated, obscuring important information.
