### ISSUE TITLE
getting error when trying to create portals using worldedit item

### ISSUE THREAD

**Issue by kanthos88tr** [Multiverse/Multiverse-Portals#501]
when I enter the command to create a portal /mvp create portalname w:worldname

![image](https://user-images.githubusercontent.com/48741086/54653387-e89f2280-4a90-11e9-8b41-5d25bdd94147.png)

19.03 21:44:51 [Server] INFO [PermissionsEx] Enabling PermissionsEx v1.23.4
19.03 21:44:51 [Server] INFO [PermissionsEx] Initializing file backend
19.03 21:44:51 [Server] INFO [PermissionsEx] Permissions file successfully reloaded
19.03 21:44:52 [Server] INFO [WorldEdit] Enabling WorldEdit v7.0.0-beta-03;b192466
19.03 21:44:52 [Server] INFO [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_13_R2 as the Bukkit adapter
19.03 21:44:52 [Server] INFO WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
19.03 21:44:52 [Server] INFO [PluginConstructorAPI] Enabling PluginConstructorAPI v1.0.51
19.03 21:44:52 [Server] INFO [KeepItems] Enabling KeepItems v1.3.2
19.03 21:44:52 [Server] INFO [Multiverse-Core] Enabling Multiverse-Core v2.5.0-b727
19.03 21:44:52 [Server] INFO Preparing start region for level 3 (Seed: 3703327848846685321)
19.03 21:44:53 [Server] INFO Preparing start region for level 4 (Seed: -2561953787892200822)
19.03 21:44:54 [Server] INFO Preparing start region for level 5 (Seed: -6757303966475065739)
19.03 21:44:55 [Server] INFO Preparing start region for level 6 (Seed: -3345610656035453256)
19.03 21:44:56 [Server] INFO Preparing spawn area for creative, 28%
19.03 21:44:56 [Server] INFO [Multiverse-Core] 7 - World(s) loaded.
19.03 21:44:56 [Server] INFO [Multiverse-Core] Version 2.5.0-b727 (API v20) Enabled - By Rigby, fernferret, lithium3141, main-- and dumptruckman
19.03 21:44:56 [Server] INFO [Multiverse-Portals] Enabling Multiverse-Portals v2.5.0-b751
19.03 21:44:56 [Server] INFO [Multiverse-Portals] - Version 2.5.0-b751 Enabled - By Rigby and fernferret
19.03 21:44:56 [Server] INFO [MVPLogging] 7 - Portals(s) loaded
19.03 21:44:56 [Server] WARN [Multiverse-Core] Portal max1 has an invalid DESTINATION!
19.03 21:44:56 [Server] ERROR Error occurred while enabling Multiverse-Portals v2.5.0-b751 (Is it up to date?)
19.03 21:44:56 [Server] INFO java.lang.NoClassDefFoundError: com/sk89q/worldedit/bukkit/WorldEditAPI
19.03 21:44:56 [Server] INFO at com.onarandombox.MultiversePortals.WorldEditConnection.connect(WorldEditConnection.java:47) ~[?:?]
19.03 21:44:56 [Server] INFO at com.onarandombox.MultiversePortals.MultiversePortals.checkForWorldEdit(MultiversePortals.java:174) ~[?:?]
19.03 21:44:56 [Server] INFO at com.onarandombox.MultiversePortals.MultiversePortals.onEnable(MultiversePortals.java:141) ~[?:?]
19.03 21:44:56 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:44:56 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:331) [craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:44:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:44:56 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:418) [craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:44:56 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:344) [craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:44:56 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:575) [craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:44:56 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:537) [craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:44:56 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:415) [craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:44:56 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:270) [craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:44:56 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:680) [craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:44:56 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
19.03 21:44:56 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.bukkit.WorldEditAPI
19.03 21:44:56 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191]
19.03 21:44:56 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:130) ~[craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:44:56 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:76) ~[craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:44:56 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
19.03 21:44:56 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
19.03 21:44:56 [Server] INFO ... 14 more
19.03 21:44:56 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
19.03 21:44:57 [Server] Startup Done (8.984s)! For help, type "help"

19.03 21:49:23 [Server] INFO Kanthos88 issued server command: /mvpcreate test1 w:threadraiders
19.03 21:49:23 [Server] ERROR null
19.03 21:49:23 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mvpcreate' in plugin Multiverse-Portals v2.5.0-b751
19.03 21:49:23 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:49:23 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:138) ~[craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:49:23 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:679) ~[craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:49:23 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1587) ~[craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:49:23 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1447) ~[craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:49:23 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(SourceFile:37) ~[craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:49:23 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(SourceFile:9) ~[craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:49:23 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:49:23 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
19.03 21:49:23 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
19.03 21:49:23 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:49:23 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:843) [craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:49:23 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:382) [craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:49:23 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:796) [craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:49:23 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:699) [craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:49:23 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
19.03 21:49:23 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.bukkit.WorldEditPlugin.getSelection(Lorg/bukkit/entity/Player;)Lcom/sk89q/worldedit/bukkit/selections/Selection;
19.03 21:49:23 [Server] INFO at com.onarandombox.MultiversePortals.WorldEditConnection.getSelection(WorldEditConnection.java:74) ~[?:?]
19.03 21:49:23 [Server] INFO at com.onarandombox.MultiversePortals.WorldEditConnection.isSelectionAvailable(WorldEditConnection.java:121) ~[?:?]
19.03 21:49:23 [Server] INFO at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:165) ~[?:?]
19.03 21:49:23 [Server] INFO at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
19.03 21:49:23 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
19.03 21:49:23 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
19.03 21:49:23 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
19.03 21:49:23 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
19.03 21:49:23 [Server] INFO at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:358) ~[?:?]
19.03 21:49:23 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.13.2.jar:git-Bukkit-e693496]
19.03 21:49:23 [Server] INFO ... 15 more

**Comment by kanthos88tr** [comment]
I found the fix! 
I installed multiverse core 2.60
multiverse portals snapshot 2.52
world edit 7.0.0 beta
