### ISSUE TITLE
Version 1.14.2 Problem

### ISSUE THREAD

**Issue by 0a6** [Multiverse/Multiverse-Portals#507]
[Server thread/ERROR]: Error occurred while enabling Multiverse-Portals v3.0.0-SNAPSHOT-b788 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/TravelAgent
        at com.onarandombox.MultiversePortals.MultiversePortals.registerEvents(MultiversePortals.java:153) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onEnable(MultiversePortals.java:145) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [server.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [server.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [server.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [server.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [server.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [server.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [server.jar:git-Spigot-093165d-ba575a5]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.ClassNotFoundException: org.bukkit.TravelAgent
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[server.jar:git-Spigot-093165d-ba575a5]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        ... 11 more

What is this supposed to mean?
Is it that it doesn't work is Spigot 1.14.2?

**Comment by Jadiction** [comment]
Update to the latest dev build version of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists.
