### ISSUE TITLE
Cant Create Portals

### ISSUE THREAD

**Issue by NbNightGamer** [Multiverse/Multiverse-Portals#509]
This is the log in the console:
[21:44:50 INFO]: DefensiveDuck issued server command: /mvpcreate 2
[21:44:50 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvpcreate' in plugin Multiverse-Portals v3.0.0-SNAPSHOT-b788
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:138) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:682) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1579) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1439) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(SourceFile:37) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(SourceFile:9) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:838) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:382) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:791) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:694) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.regions.Region.getMinimumPoint()Lcom/sk89q/worldedit/math/BlockVector3;
        at com.onarandombox.MultiversePortals.WorldEditConnection.getSelectionMinPoint(WorldEditConnection.java:118) ~[?:?]
        at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:166) ~[?:?]
        at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
        at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
        at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
        at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
        at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:372) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        ... 15 more

Thank you in advance

**Comment by Jadiction** [comment]
Hm, I can't seem to replicate this. Did you update all the Multiverse plugins from the dev builds? Are you using WorldEdit? Update that too, if so.

**Comment by NbNightGamer** [comment]
> Hm, I can't seem to replicate this. Did you update all the Multiverse plugins from the dev builds? Are you using WorldEdit? Update that too, if so.

Yes I updated all the multiverse plugins and i have updated to the latest version of FAWE.

**Comment by Jadiction** [comment]
It shows Multiverse-Portals 3.0.0. The latest right now is 4.0.0. Go to the dev builds for MV-Core and MV-Portals and get the 4.0.0 versions.

**Comment by NbNightGamer** [comment]
> It shows Multiverse-Portals 3.0.0. The latest right now is 4.0.0. Go to the dev builds for MV-Core and MV-Portals and get the 4.0.0 versions.

Still doesn't work :'[




[22:57:06 INFO]: DefensiveDuck issued server command: /mvp create 1
[22:57:06 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v4.0.0-SNAPSHOT-b796
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:138) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:682) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1579) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1439) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(SourceFile:37) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(SourceFile:9) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:838) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:382) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:791) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:694) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.regions.Region.getMinimumPoint()Lcom/sk89q/worldedit/math/BlockVector3;
        at com.onarandombox.MultiversePortals.WorldEditConnection.getSelectionMinPoint(WorldEditConnection.java:118) ~[?:?]
        at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:166) ~[?:?]
        at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
        at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
        at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
        at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
        at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:361) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        ... 15 more
>

**Comment by Jadiction** [comment]
Can you try loading the server in without WorldEdit and seeing if it works? It looks like a WorldEdit issue.

**Comment by Jadiction** [comment]
Going to assume this is solved - closing the ticket. If you're still having issues, please don't hesitate to make another ticket or for a faster response, you can also receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
