### ISSUE TITLE
After updating server to 1.14.3 then downloading recent file of the plugin; it doesn't work

### ISSUE THREAD

**Issue by joshlemay** [Multiverse/Multiverse-Portals#512]
Here's my console when I type /mvp

```02.07 12:26:17 [Server] ERROR null
02.07 12:26:17 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'mvp' in plugin Multiverse-Portals v4.0.0-b799 - plugin is disabled.
02.07 12:26:17 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.14.3.jar:git-Paper-111]
02.07 12:26:17 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.3.jar:git-Paper-111]
02.07 12:26:17 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736) ~[patched_1.14.3.jar:git-Paper-111]
02.07 12:26:17 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1831) ~[patched_1.14.3.jar:git-Paper-111]
02.07 12:26:17 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1639) ~[patched_1.14.3.jar:git-Paper-111]
02.07 12:26:17 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.3.jar:git-Paper-111]
02.07 12:26:17 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.3.jar:git-Paper-111]
02.07 12:26:17 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-111]
02.07 12:26:17 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-111]
02.07 12:26:17 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-111]
02.07 12:26:17 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-111]
02.07 12:26:17 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-111]
02.07 12:26:17 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-111]
02.07 12:26:17 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-111]
02.07 12:26:17 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.3.jar:git-Paper-111]
02.07 12:26:17 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979) ~[patched_1.14.3.jar:git-Paper-111]
02.07 12:26:17 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-111]
02.07 12:26:17 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]```

**Comment by dumptruckman** [comment]
We need to see the full error to be able to assist. This is only part of the error. The rest will begin with `Caused by`

**Comment by ZolaBaiss** [comment]
Getting the following:

[14:30:27] [Server thread/ERROR]: Could not load 'plugins/Multiverse-Portals-4.0.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/onarandombox/commandhandler/Command
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.14.3.jar:git-Spigot-
4d2f30f-f1f3355]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:333) ~[spigot-1.14.3.jar:git-Spigot
-4d2f30f-f1f3355]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:252) [spigot-1.14.3.jar:git-Spigot
-4d2f30f-f1f3355]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:347) [spigot-1.14.3.jar:git-Spigot-4
d2f30f-f1f3355]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:194) [spigot-1.14.3.jar:git-Spigot-4d
2f30f-f1f3355]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:760) [spigot-1.14.3.jar:git-Spigot-4d2
f30f-f1f3355]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: com/onarandombox/commandhandler/Command
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_101]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigot-1.14.3.jar:git-Spigot-4d2
f30f-f1f3355]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.14.3.jar:git-Spigot-
4d2f30f-f1f3355]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.onarandombox.commandhandler.Command
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.14.3.jar:git-Spigot
-4d2f30f-f1f3355]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.3.jar:git-Spigot-
4d2f30f-f1f3355]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_101]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigot-1.14.3.jar:git-Spigot-4d2
f30f-f1f3355]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.14.3.jar:git-Spigot-
4d2f30f-f1f3355]
        ... 6 more

**Comment by dumptruckman** [comment]
You need to have Multiverse-Core if you want to use Multiverse-Portals.
