### ISSUE TITLE
NPE on server start-up

### ISSUE THREAD

**Issue by SlimeDog** [Multiverse/Multiverse-Portals#525]
Spigot 1.14.4 latest (Jenkins 2459) git-Spigot-065a373-6ed8a18 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Multiverse-Core version 4.1.1-SNAPSHOT-b777
Multiverse-Portals version 4.1.1-SNAPSHOT-b807

On server start-up:
```
[06:57:56] [Server thread/INFO]: [Multiverse-Portals] Enabling Multiverse-Portals v4.1.1-SNAPSHOT-b807
[06:57:56] [Server thread/ERROR]: Error occurred while enabling Multiverse-Portals v4.1.1-SNAPSHOT-b807 (Is it up to date?)
java.lang.NullPointerException: null
        at com.onarandombox.MultiversePortals.MVPortal.setCurrency(MVPortal.java:206) ~[?:?]
        at com.onarandombox.MultiversePortals.MVPortal.init(MVPortal.java:79) ~[?:?]
        at com.onarandombox.MultiversePortals.MVPortal.<init>(MVPortal.java:66) ~[?:?]
        at com.onarandombox.MultiversePortals.MVPortal.loadMVPortalFromConfig(MVPortal.java:176) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.loadPortals(MultiversePortals.java:221) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onEnable(MultiversePortals.java:140) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.4.jar-2019-08-30-0655:git-Spigot-065a373-6ed8a18]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.4.jar-2019-08-30-0655:git-Spigot-065a373-6ed8a18]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.14.4.jar-2019-08-30-0655:git-Spigot-065a373-6ed8a18]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.4.jar-2019-08-30-0655:git-Spigot-065a373-6ed8a18]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.4.jar-2019-08-30-0655:git-Spigot-065a373-6ed8a18]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot-1.14.4.jar-2019-08-30-0655:git-Spigot-065a373-6ed8a18]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot-1.14.4.jar-2019-08-30-0655:git-Spigot-065a373-6ed8a18]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot-1.14.4.jar-2019-08-30-0655:git-Spigot-065a373-6ed8a18]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by mrcoffee1026** [comment]
This error goes away if you switch to multiverse core version 4.1.0.

**Comment by Jadiction** [comment]
This will be fixed soon once the [latest PR](https://github.com/Multiverse/Multiverse-Portals/pull/526) is merged. Won't be too long.

**Comment by Jadiction** [comment]
This has been fixed.
