### ISSUE TITLE
PlayerMoveEvent Exception when Player in Cart Rides through Portal Linking Worlds

### ISSUE THREAD

**Issue by mattc4t** [Multiverse/Multiverse-Portals#528]
Players riding a cart will get stuck and must leave the Spigot server to get unstuck, if riding a cart through portals linking different worlds.  This problem surfaced in at least Multiverse-Portals 4.0.0 and is also repeatable in 4.1.0.

I created a very stripped-down Minecraft server running Spigot 1.14.4.  Using default configurations for Spigot and Multiverse plugins.  (The problem is also repeatable in Paper with similar symptoms):

[23:21:04] [Server thread/INFO]: Plugins (2): **Multiverse-Core, Multiverse-Portals**

In console, I noted an exception related to PlayerMoveEvent.  I have also seen an exception related to VehicleMoveEvent on a server loaded with many plugins:

[23:07:09] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Multiverse-Portals v4.1.0-b805
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:986) ~[spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
        at net.minecraft.server.v1_14_R1.PacketPlayInFlying.a(SourceFile:126) ~[spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
        at net.minecraft.server.v1_14_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
        at com.onarandombox.MultiversePortals.PortalPlayerSession.doTeleportPlayer(PortalPlayerSession.java:101) ~[?:?]
        at com.onarandombox.MultiversePortals.listeners.MVPPlayerMoveListener.playerMove(MVPPlayerMoveListener.java:61) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-56f8471-7554e08]
        ... 17 more

**Comment by benwoo1110** [comment]
Closing as its probably fixed by the server software already and no new reports of similar issues
