### ISSUE TITLE
Multiverse-Portal on paper

### ISSUE THREAD

**Issue by JosepBove** [Multiverse/Multiverse-Portals#530]
I am trying to install multiverse-portals in paper. Currently I have multiverse-core 4.1.0 and it works perfectly so I decided to use the multiverse-portals 4.1.0 version. When I add the plugin I get this error in the console. Does anyone know how to solve it or the cause?

```
[22:32:08 ERROR]: Could not load 'plugins/Multiverse-portals.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/onarandombox/commandhandler/Command
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[patched_1.14.4.jar:git-Paper-238]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337) ~[patched_1.14.4.jar:git-Paper-238]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257) ~[patched_1.14.4.jar:git-Paper-238]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) ~[patched_1.14.4.jar:git-Paper-238]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-238]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-238]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NoClassDefFoundError: com/onarandombox/commandhandler/Command
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_232]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_232]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63) ~[patched_1.14.4.jar:git-Paper-238]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.14.4.jar:git-Paper-238]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.onarandombox.commandhandler.Command
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_232]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.4.jar:git-Paper-238]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-238]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_232]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_232]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63) ~[patched_1.14.4.jar:git-Paper-238]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.14.4.jar:git-Paper-238]
```

**Comment by xManInWhitex** [comment]
I think your downloaded jar file is corrupted.
Please try downloading it again.

Which paper version do you use?

**Comment by BlackCatTB** [comment]
Hey, so I had the same problem like @JosepBove had, and I resolved it by using both the dev version of [mv-core](https://ci.onarandombox.com/job/Multiverse-Core/) and [mv-portals](http://ci.onarandombox.com/job/Multiverse-Portals/) on my 1.16.1 paper 101 server.
Hope this saved some trail and error time ;D
