### ISSUE TITLE
Multiverse Portals 2.5.0 won't load (Could not initialize class)

### ISSUE THREAD

**Issue by GoldenretriverYT** [Multiverse/Multiverse-Portals#536]
When I tried to load MV-Portal, it does not work.
MV-Core and MV-Portal are both version 2.5.0.

Log:
`[12:30:25 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: Could not initialize class com.onarandombox.MultiversePortals.MultiversePortals
[12:30:25 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133)
[12:30:25 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327)
[12:30:25 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:356)
[12:30:25 WARN]:        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[12:30:25 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[12:30:25 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:30:25 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[12:30:25 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[12:30:25 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399)
[12:30:25 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234)
[12:30:25 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[12:30:25 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[12:30:25 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[12:30:25 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:30:25 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:30:25 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[12:30:25 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[12:30:25 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[12:30:25 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[12:30:25 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[12:30:25 WARN]:        at java.lang.Thread.run(Thread.java:748)
[12:30:25 WARN]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.onarandombox.MultiversePortals.MultiversePortals
[12:30:25 WARN]:        at java.lang.Class.forName0(Native Method)
[12:30:25 WARN]:        at java.lang.Class.forName(Class.java:348)
[12:30:25 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78)
[12:30:25 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
[12:30:25 WARN]:        ... 20 more`

**Comment by GoldenretriverYT** [comment]
Was fixed by restarting the server.
