### ISSUE TITLE
Paper server support ?

### ISSUE THREAD

**Issue by JeanMarcZimmer** [Multiverse/Multiverse-Portals#555]
It's quite unclear, which versions and types of server are supported.

On [Paper](https://papermc.io/downloads) (builds 354 & 361 tested, both had the error), Minecraft version 1.15.2, I get the following error : 
Paper is said to just be a fork of Spigot, faster and supports API versions of plugins. Multiverse-core doesn't have such version by the way.
```
[21:46:56 ERROR]: Could not load 'plugins/Multiverse-Portals-4.1.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/onarandombox/commandhandler/Command
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.15.2.jar:git-Paper-354]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-354]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.15.2.jar:git-Paper-354]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-354]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/onarandombox/commandhandler/Command
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:427) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.15.2.jar:git-Paper-354]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.15.2.jar:git-Paper-354]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.onarandombox.commandhandler.Command
	at java.net.URLClassLoader.findClass(URLClassLoader.java:435) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-354]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-354]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:427) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.15.2.jar:git-Paper-354]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.15.2.jar:git-Paper-354]
	... 6 more
```

**Comment by JeanMarcZimmer** [comment]
By the way, the server warns about a deprecated listener : 
```
[22:04:52 WARN]: [Multiverse-Core] "Multiverse-Core v2.5-b719" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--].
```

**Comment by benwoo1110** [comment]
Can you send you full startup log?

**Comment by nicegamer7** [comment]
I think this would be caused by using an outdated version of MV Core. From your second comment, I can see you're using `v2.5-b719`, which is too old to supprt MV Portals v4.1.0. That warning about the deprecated listener can be safely ignored too.

The latest version of Multiverse can be found [here](https://dev.bukkit.org/projects/multiverse-core).
And by the way, Multiverse is fully compatible with Paper.

**Comment by JeanMarcZimmer** [comment]
> I think this would be caused by using an outdated version of MV Core. From your second comment, I can see you're using `v2.5-b719`, which is too old to support MV Portals v4.1.0. That warning about the deprecated listener can be safely ignored too.
> 
> The latest version of Multiverse can be found [here](https://dev.bukkit.org/projects/multiverse-core).
> And by the way, Multiverse is fully compatible with Paper.

Indeed.
Apparently, the Spigot website's direct download isn't up-to-date, or I messed up when replacing the files. Oh well.

Sorry for the useless pings people, and thank you for your help !
