### ISSUE TITLE
Could not pass event PlayerMoveEvent

### ISSUE THREAD

**Issue by crizyx** [Multiverse/Multiverse-Portals#559]
Hello I have encountered this error about the PlayerMoveEvent with the Paper 1.16.1 build 98 and Multiverse-Portals v4.1.0-b805.

```JAVA
>.... [13:26:40 ERROR]: Could not pass event PlayerMoveEvent to Multiverse-Portals v4.1.0-b805
java.lang.NullPointerException: null
at net.minecraft.server.v1_16_R1.World.isOutsideWorld(World.java:270) ~[patched_1.16.1.jar:git-Paper-98]
at net.minecraft.server.v1_16_R1.World.getType(World.java:715) ~[patched_1.16.1.jar:git-Paper-98]
at net.minecraft.server.v1_16_R1.PlayerList.moveToWorld(PlayerList.java:857) ~[patched_1.16.1.jar:git-Paper-98]
at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.teleport(CraftPlayer.java:813) ~[patched_1.16.1.jar:git-Paper-98]
at org.bukkit.craftbukkit.v1_16_R1.entity.CraftEntity.teleport(CraftEntity.java:522) ~[patched_1.16.1.jar:git-Paper-98]
at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.safelyTeleport(SimpleSafeTTeleporter.java:215) ~[?:?]
at com.onarandombox.MultiversePortals.listeners.PlayerListenerHelper.performTeleport(PlayerListenerHelper.java:43) ~[?:?]
at com.onarandombox.MultiversePortals.listeners.MVPPlayerMoveListener.playerMove(MVPPlayerMoveListener.java:135) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor128.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-98]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-98]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-98]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-98]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1163) ~[patched_1.16.1.jar:git-Paper-98]
at net.minecraft.server.v1_16_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.16.1.jar:git-Paper-98]
at net.minecraft.server.v1_16_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-98]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-98]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-98]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-98]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-98]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-98]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-98]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-98]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-98]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-98]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-98]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-98]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```
Can you help me ?
Thanks.

**Comment by nicegamer7** [comment]
This is a Spigot/Paper issue, see Multiverse/Multiverse-Core#2356.
