### ISSUE TITLE
Can't create portals

### ISSUE THREAD

**Issue by Hanse00** [Multiverse/Multiverse-Portals#89]
I have world edit installed, when ever I try to make a portal I get a "An internal error has occurred while attempting to preform this command"
No console errors or anything in the multiverse log.

Multiverse-Core: Loaded Worlds: 4
Multiverse-Core: Multiverse Plugins Loaded: 1
Multiverse-Core: Economy being used: Simple Item Economy
Multiverse-Core: Permissions Plugin: Bukkit Permissions (SuperPerms)
Multiverse-Core: Dumping Config Values: (version NOT SET)
Multiverse-Core: messagecooldown: Not yet IMPLEMENTED
Multiverse-Core: teleportcooldown: Not yet IMPLEMENTED
Multiverse-Core: worldnameprefix: true
Multiverse-Core: enforceaccess: true
Multiverse-Core: enforcegamemodes: true
Multiverse-Core: debug: 0
Multiverse-Core: Special Code: FRN002
Multiverse-Portals:  Multiverse-Portals Version: 2.1-b295
Multiverse-Portals:  Bukkit Version: git-Bukkit-1.8.1-R4-83-g24cb05a-b1556jnks (MC: 1.0.1)
Multiverse-Portals:  Loaded Portals: 0
Multiverse-Portals:  Dumping Portal Values: (version NOT SET)
Multiverse-Portals:  wand: NOT SET
Multiverse-Portals:  useonmove: NOT SET
Multiverse-Portals:  enforceportalaccess: NOT SET
Multiverse-Portals:  portalsdefaulttonether: NOT SET
Multiverse-Portals:  portalcooldown: NOT SET
Multiverse-Portals:  Special Code: FRN001

Anyone know what I'm doing wrong? Since this is probably a case of me having fucked something up (Wouldn't be the first time)

**Comment by ThesethLord** [comment]
I have a very similar problem I get the same popup when I type the command, I read through this conversation and I cannot find the problem in my script.

Can you help?

[18:49:49 INFO]: Cane Growth Modifier: 100%
[18:49:49 INFO]: Melon Growth Modifier: 100%
[18:49:49 INFO]: Mushroom Growth Modifier: 100%
[18:49:49 INFO]: Pumpkin Growth Modifier: 100%
[18:49:49 INFO]: Sapling Growth Modifier: 100%
[18:49:49 INFO]: Wheat Growth Modifier: 100%
[18:49:49 INFO]: NetherWart Growth Modifier: 100%
[18:49:49 INFO]: Vine Growth Modifier: 100%
[18:49:49 INFO]: Cocoa Growth Modifier: 100%
[18:49:49 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:49:49 INFO]: Max TNT Explosions: 100
[18:49:49 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:49:49 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617Monument: 10387313 Slime: 987234911
[18:49:49 INFO]: -------- World Settings For [world_nether] --------
[18:49:49 INFO]: Item Despawn Rate: 6000
[18:49:49 INFO]: Item Merge Radius: 2.5
[18:49:49 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:49:49 INFO]: Arrow Despawn Rate: 1200
[18:49:49 INFO]: Experience Merge Radius: 3.0
[18:49:49 INFO]: View Distance: 10
[18:49:49 INFO]: Zombie Aggressive Towards Villager: true
[18:49:49 INFO]: Nerfing mobs spawned from spawners: false
[18:49:49 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[18:49:49 INFO]: Mob Spawn Range: 4
[18:49:49 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[18:49:49 INFO]: Structure Info Saving: true
[18:49:49 INFO]: Random Lighting Updates: false
[18:49:49 INFO]: Cactus Growth Modifier: 100%
[18:49:49 INFO]: Cane Growth Modifier: 100%
[18:49:49 INFO]: Melon Growth Modifier: 100%
[18:49:49 INFO]: Mushroom Growth Modifier: 100%
[18:49:49 INFO]: Pumpkin Growth Modifier: 100%
[18:49:49 INFO]: Sapling Growth Modifier: 100%
[18:49:49 INFO]: Wheat Growth Modifier: 100%
[18:49:49 INFO]: NetherWart Growth Modifier: 100%
[18:49:49 INFO]: Vine Growth Modifier: 100%
[18:49:49 INFO]: Cocoa Growth Modifier: 100%
[18:49:49 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:49:49 INFO]: Max TNT Explosions: 100
[18:49:49 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:49:49 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617Monument: 10387313 Slime: 987234911
[18:49:49 INFO]: -------- World Settings For [world_the_end] --------
[18:49:49 INFO]: Item Despawn Rate: 6000
[18:49:49 INFO]: Item Merge Radius: 2.5
[18:49:49 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:49:49 INFO]: Arrow Despawn Rate: 1200
[18:49:49 INFO]: Experience Merge Radius: 3.0
[18:49:49 INFO]: View Distance: 10
[18:49:49 INFO]: Zombie Aggressive Towards Villager: true
[18:49:49 INFO]: Nerfing mobs spawned from spawners: false
[18:49:49 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[18:49:49 INFO]: Mob Spawn Range: 4
[18:49:49 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[18:49:49 INFO]: Structure Info Saving: true
[18:49:49 INFO]: Random Lighting Updates: false
[18:49:49 INFO]: Cactus Growth Modifier: 100%
[18:49:49 INFO]: Cane Growth Modifier: 100%
[18:49:49 INFO]: Melon Growth Modifier: 100%
[18:49:49 INFO]: Mushroom Growth Modifier: 100%
[18:49:49 INFO]: Pumpkin Growth Modifier: 100%
[18:49:49 INFO]: Sapling Growth Modifier: 100%
[18:49:49 INFO]: Wheat Growth Modifier: 100%
[18:49:49 INFO]: NetherWart Growth Modifier: 100%
[18:49:49 INFO]: Vine Growth Modifier: 100%
[18:49:49 INFO]: Cocoa Growth Modifier: 100%
[18:49:49 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:49:49 INFO]: Max TNT Explosions: 100
[18:49:49 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:49:49 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617Monument: 10387313 Slime: 987234911
[18:49:50 INFO]: Preparing start region for level 0 (Seed: -2904687141688286037)
[18:49:51 INFO]: Preparing spawn area: 0%
[18:49:52 INFO]: Preparing spawn area: 11%
[18:49:53 INFO]: Preparing spawn area: 25%
[18:49:54 INFO]: Preparing spawn area: 41%
[18:49:55 INFO]: Preparing spawn area: 57%
[18:49:56 INFO]: Preparing spawn area: 70%
[18:49:57 INFO]: Preparing spawn area: 89%
[18:49:57 INFO]: Preparing start region for level 1 (Seed: -2904687141688286037)
[18:49:58 INFO]: Preparing spawn area: 15%
[18:49:59 INFO]: Preparing spawn area: 34%
[18:50:00 INFO]: Preparing spawn area: 51%
[18:50:01 INFO]: Preparing spawn area: 72%
[18:50:02 INFO]: Preparing spawn area: 90%
[18:50:03 INFO]: Preparing start region for level 2 (Seed: -2904687141688286037)
[18:50:04 INFO]: [WorldEdit] Enabling WorldEdit v6.1.5;4651611
[18:50:04 INFO]: WEPIF: Using the Bukkit Permissions API.
[18:50:04 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_11_R1 as the Bukkit adapter
[18:50:04 INFO]: [Lockette] Enabling Lockette v1.8.23
[18:50:04 INFO]: [Lockette] Version 1.8.23 is being enabled!  Yay!  (Core version 1.3.5)
[18:50:04 INFO]: minor >
[18:50:04 INFO]: [Lockette] Detected Bukkit version [v1_11_R1] ok.
[18:50:04 INFO]: [Lockette] Custom lockable block list: [116, 84, 57, 145, 154]
[18:50:04 INFO]: [Lockette] Ignoring linked plugins: [mcMMO]
[18:50:04 INFO]: [Lockette] Loading strings file for English by Acru
[18:50:04 INFO]: [Lockette] Using ops file for admin permissions.
[18:50:04 INFO]: [Lockette] Ready to protect your containers.
[18:50:04 INFO]: [Multiverse-Core] Enabling Multiverse-Core v2.5-b699
[18:50:05 INFO]: -------- World Settings For [Survivalness] --------
[18:50:05 INFO]: Item Despawn Rate: 6000
[18:50:05 INFO]: Item Merge Radius: 2.5
[18:50:05 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:50:05 INFO]: Arrow Despawn Rate: 1200
[18:50:05 INFO]: Experience Merge Radius: 3.0
[18:50:05 INFO]: View Distance: 10
[18:50:05 INFO]: Zombie Aggressive Towards Villager: true
[18:50:05 INFO]: Nerfing mobs spawned from spawners: false
[18:50:05 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[18:50:05 INFO]: Mob Spawn Range: 4
[18:50:05 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[18:50:05 INFO]: Structure Info Saving: true
[18:50:05 INFO]: Random Lighting Updates: false
[18:50:05 INFO]: Cactus Growth Modifier: 100%
[18:50:05 INFO]: Cane Growth Modifier: 100%
[18:50:05 INFO]: Melon Growth Modifier: 100%
[18:50:05 INFO]: Mushroom Growth Modifier: 100%
[18:50:05 INFO]: Pumpkin Growth Modifier: 100%
[18:50:05 INFO]: Sapling Growth Modifier: 100%
[18:50:05 INFO]: Wheat Growth Modifier: 100%
[18:50:05 INFO]: NetherWart Growth Modifier: 100%
[18:50:05 INFO]: Vine Growth Modifier: 100%
[18:50:05 INFO]: Cocoa Growth Modifier: 100%
[18:50:05 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:50:05 INFO]: Max TNT Explosions: 100
[18:50:05 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:50:05 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617Monument: 10387313 Slime: 987234911
[18:50:05 INFO]: Preparing start region for level 3 (Seed: 5564268083157372005)
[18:50:14 INFO]: [Multiverse-Core] 4 - World(s) loaded.
[18:50:15 INFO]: [Multiverse-Core] Version 2.5-b699 (API v19) Enabled - By Rigby, fernferret, lithium3141 and main--
[18:50:15 INFO]: [WorldGuard] Enabling WorldGuard v6.1.3-SNAPSHOT;c904242
[18:50:15 INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[18:50:15 INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[18:50:15 INFO]: [WorldGuard] (world) Lava fire is blocked.
[18:50:15 INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[18:50:15 INFO]: [WorldGuard] Loaded configuration for world 'world'
[18:50:15 INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[18:50:15 INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[18:50:15 INFO]: [WorldGuard] (world_nether) Lava fire is blocked.
[18:50:15 INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[18:50:15 INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[18:50:15 INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[18:50:15 INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[18:50:15 INFO]: [WorldGuard] (world_the_end) Lava fire is blocked.
[18:50:15 INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[18:50:15 INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[18:50:15 INFO]: [WorldGuard] (Survivalness) TNT ignition is PERMITTED.
[18:50:15 INFO]: [WorldGuard] (Survivalness) Lighters are PERMITTED.
[18:50:15 INFO]: [WorldGuard] (Survivalness) Lava fire is blocked.
[18:50:15 INFO]: [WorldGuard] (Survivalness) Fire spread is UNRESTRICTED.
[18:50:15 INFO]: [WorldGuard] Loaded configuration for world 'Survivalness'
[18:50:15 INFO]: [WorldGuard] Loading region data...
[18:50:15 INFO]: [CraftBook] Enabling CraftBook v3.9-SNAPSHOT
[18:50:15 INFO]: [CraftBook] Loading persistent data from YAML!
[18:50:16 INFO]: [CraftBook] The Auto-Updater is disabled for your version!
[18:50:16 INFO]: [ShopChest] Enabling ShopChest v1.11.1
[18:50:16 INFO]: [ShopChest] Using SQLite
[18:50:16 INFO]: [ShopChest] Initialized 0 Shops
[18:50:16 INFO]: [Multiverse-Portals] Enabling Multiverse-Portals v2.4-b548
[18:50:16 INFO]: [Multiverse-Portals] - Version 2.4-b548 Enabled - By Rigby and fernferret
[18:50:16 INFO]: [Multiverse-Portals]  0 - Portals(s) loaded
[18:50:16 INFO]: Server permissions file permissions.yml is empty, ignoring it
[18:50:16 INFO]: Done (27.339s)! For help, type "help" or "?"
[18:50:16 WARN]: [Multiverse-Core] Plugin Multiverse-Core v2.5-b699 generated an exception while executing task 8
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at org.mcstats.multiverse.Metrics.postPlugin(Metrics.java:357) ~[?:?]
        at org.mcstats.multiverse.Metrics.access$400(Metrics.java:64) ~[?:?]
        at org.mcstats.multiverse.Metrics$1.run(Metrics.java:245) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_66]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[18:50:16 INFO]: [Vault] Checking for Updates ...
[18:50:16 INFO]: [ShopChest] Checking for updates...
[18:50:16 INFO]: [ShopChest] No new update available.
[18:50:17 WARN]: [CraftBook] ºcWarning! You have no mechanics enabled, the plugin will appear to do nothing until a feature is enabled!
[18:50:17 INFO]: [Vault] No new version available
[18:51:05 INFO]: UUID of player The_SethLord is 89506164-af37-499c-b4d7-874f30ede64a
[18:51:05 INFO]: The_SethLord[/192.168.2.105:50669] logged in with entity id 432 at ([Survivalness]-206.52602408345476, 64.91368245287414, 87.30364239434572)
>/mvp create Lobby world
[18:52:26 INFO]: Unknown command. Type "/help" for help.
>/mvp create Lobby world
[18:52:29 INFO]: Unknown command. Type "/help" for help.
[18:52:46 INFO]: The_SethLord issued server command: /mvp create lobby world
[18:52:46 INFO]: WEAPI
[18:52:46 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.4-b548
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;
        at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:169) ~[?:?]
        at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:317) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        ... 15 more
[18:53:56 INFO]: The_SethLord issued server command: /purge
[18:54:02 INFO]: The_SethLord issued server command: /mvp pruge
[18:54:22 INFO]: The_SethLord issued server command: /mvp purge
[18:54:31 INFO]: The_SethLord issued server command: /mvp purge all all
[18:54:40 INFO]: The_SethLord issued server command: /mvp purge all all
[18:54:49 INFO]: The_SethLord issued server command: /mvp purge all creeper
[18:55:18 WARN]: [CraftBook] ºcWarning! You have no mechanics enabled, the plugin will appear to do nothing until a feature is enabled!
[18:55:22 INFO]: The_SethLord issued server command: /tp The_SethLord world
[18:55:22 INFO]: [The_SethLord: Entity 'world' cannot be found]
[18:55:26 INFO]: The_SethLord issued server command: /tp The_SethLord world
[18:55:26 INFO]: [The_SethLord: Entity 'world' cannot be found]
[18:55:35 INFO]: The_SethLord issued server command: /mvp tp The_SethLord world
[18:55:38 INFO]: The_SethLord issued server command: /mvp tp The_SethLord world
[18:55:43 INFO]: The_SethLord issued server command: /mv help
[18:55:49 INFO]: The_SethLord issued server command: /mv help 2
[18:56:02 INFO]: The_SethLord issued server command: /mv tp The_SethLord world
[18:56:19 INFO]: The_SethLord issued server command: /gamemode 1
[18:56:19 INFO]: [The_SethLord: Set own game mode to Creative Mode]
[18:56:38 INFO]: The_SethLord issued server command: /mv create
[18:56:57 INFO]: The_SethLord issued server command: /mvp create
[19:00:20 WARN]: [Multiverse-Core] Plugin Multiverse-Core v2.5-b699 generated an exception while executing task 8
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at org.mcstats.multiverse.Metrics.postPlugin(Metrics.java:357) ~[?:?]
        at org.mcstats.multiverse.Metrics.access$400(Metrics.java:64) ~[?:?]
        at org.mcstats.multiverse.Metrics$1.run(Metrics.java:245) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_66]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[19:00:20 WARN]: [CraftBook] ºcWarning! You have no mechanics enabled, the plugin will appear to do nothing until a feature is enabled!
>
