### ISSUE TITLE
Portal Error

### ISSUE THREAD

**Issue by ghost** [Multiverse/Multiverse-Portals#99]
This error shows the console randomly. I have no idea what the people do to get this error.

```
Could not pass event PLAYER_PORTAL to Multiverse-Portals
java.lang.NullPointerException
	at com.onarandombox.MultiverseCore.utils.SafeTTeleporter.findPortalBlockNextTo(SafeTTeleporter.java:289)
	at com.onarandombox.MultiversePortals.listeners.MVPPlayerListener.onPlayerPortal(MVPPlayerListener.java:247)
	at org.bukkit.plugin.java.JavaPluginLoader$10.execute(JavaPluginLoader.java:328)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
	at net.minecraft.server.ServerConfigurationManager.changeDimension(ServerConfigurationManager.java:337)
	at net.minecraft.server.EntityPlayer.e(EntityPlayer.java:336)
	at net.minecraft.server.BlockEnderPortal.a(SourceFile:55)
	at net.minecraft.server.Entity.move(Entity.java:613)
	at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:332)
	at net.minecraft.server.Packet10Flying.a(SourceFile:126)
	at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
	at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:93)
	at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:527)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
	at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
```

**Comment by FernFerret** [comment]
Closing because user was deleted.
